### ISSUE TITLE
Mouse crash with AppleWin1.26.3.1

### ISSUE THREAD

**Issue by MarcoVerpelli** [AppleWin/AppleWin#495] opened 2017-10-15 16:33 UTC
Hello,
any program I've tried crashed into the monitor at CF38 when you exit.
I wrote 'exit' not 'quit' because also a program like DazzleDraw crash and DazzeDraw ask to reboot not to quit to ProDOS.

Thank you
Marco

**Comment by tomcw** [comment] 2017-10-16 00:13
Hi Marco,
I can't reproduce this.
I've tried DazzleDraw and Fantavision - both use the mouse, and for both when I quit, they reboot. I never see a crash.

Do you have an unusual configuration?
Just before the crash (eg. at the 'quit' menu), can you create a save-state file and attach to this issue. You will need to rename to .txt.

**Comment by MarcoVerpelli** [comment] 2017-10-16 08:34
Save state & disk image:
https://drive.google.com/file/d/0Bz0ReUsiwYcpMFg4TWsyT2N3YjQ/view?usp=sharing

There must be a conflict between mouse and NSC, 
If I do not load the driver for the clock: all OK

Marco

**Comment by tomcw** [comment] 2017-10-16 17:17
Thanks for the repro - this is a regression at 1.26.3.1 in 3a5bf01.
To avoid this you can switch back to 1.26.3.0 for now.
I will fix & do a new release soon.

**Comment by MarcoVerpelli** [comment] 2017-10-16 18:08
No problem. I always try the latest release. This time I'm a couple of weeks late.

**Comment by tomcw** [comment] 2017-10-21 20:33
Hi Marco,
This issue is now fixed in this new experimental build: [v1.26.3.2](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.2).

**Comment by MarcoVerpelli** [comment] 2017-10-22 07:46
OK, passed all my usual tests.

**Comment by tomcw** [comment] 2017-10-22 09:24
Thanks for confirming.

**Closed by tomcw** 2017-10-22 09:24 UTC
Labels: 1.26.3.1, bug
