### ISSUE TITLE
Configuration button, Disk tab, Select Disk... (using combo-box)

### ISSUE THREAD

**Issue by TommyGH** [AppleWin/AppleWin#334] opened 2016-08-24 18:19 UTC
I have two interesting observations regarding the behavior for selecting floppy disk images from the Disk tab.

AppleWin 1.25.0.4+ (from source 8/21/2016.  Not to be confused with 1.25.0.4 from 4/24/2015.)

Observation 1:

Start AppleWin.
Click the Configuration button (or F8), Disk tab, and Eject Disk for both floppies.
From Disk1 drop down, "Select Disk" and select a valid "image.dsk".
From Disk2 drop down, "Select Disk" and choose the exact disk image.
Cool, the disk image is removed from Disk1 and is now in Disk2.
For Disk1 drop down, "Select Disk" and choose the exact disk image.
Cool, the disk image switches places again.

So far everything is working as I'd expect.

Leave "image.dsk" in Disk1 and Click "OK".  Close AppleWin.

Start AppleWin again.
Click Configuration, Disk, and notice "image.dsk" in Disk1.
From Disk2 drop down, "Select Disk" and choose the same disk image.

Hmmmm.  Instead of switching like before, an error message is displayed:

  Enhanced Apple IIe emulator
    !  Unable to open the file c:....\image.dsk
                                       [OK]

Maybe that is the way it is intended to work, but I find the different behavior "interesting".  Also, the error message isn't exactly the best for this situation.

Observation 2:

With no disk image in the combo box, you can select "Eject Disk", and then "Eject Disk" is displayed in the combobox!?  
Is it really intentional to display "Eject Disk" in the box?

Tommy

**Comment by TommyGH** [comment] 2016-08-24 19:33
Observation 3:
With no disk in the comboBox, click the down arrow (notice 2 lines displayed), and click "Select Disk" and then click "Cancel" before selecting a disk.
Now click on the comboBox down arrow again, and notice there are 3 lines displayed with the first one blank with the other two "Select Disk" and "Eject Disk".
Is it correct to have that blank line displayed?

**Comment by TommyGH** [comment] 2016-08-24 21:16
Observation 4:
This one is kind of weird.
Click "Select Disk" and "find file" dialog opens to find a disk image.
You can click the same "Select Disk" and now have TWO "Select Disk" windows open.
Now click Cancel for both "Select Disk" dialogs.
Click on the drop down combobox again and you see FOUR entries in the list.
This processing is in HandleDiskCombo().

**Comment by sicklittlemonkey** [comment] 2016-08-24 21:53
There's another one that's annoyed me in the past - though not enough to
fix it yet. Ah yes, here it is:

1. Double click on a DSK to start AppleWin. It will be in D1 and boot it.
2. Press F5 to swap disks, then close AppleWin.
3. Double click on the same DSK to start AppleWin. It will appear to be in
D1 _and_ D2. If you CATALOG,D2 it's not actually there though.

There are variations on the above, so clearly it's just the UI code that is
screwy, not the emulation.

Sorry Tommy, but I've been too busy with Real Life to look at any AppleWin
issues recently.

Hopefully Tom will get back to the new release sometime, and I'll have a
look when I can.

Cheers,
Nick.

**Comment by tomcw** [comment] 2017-05-28 18:56
Hi Nick,

Your specific bug was fixed in 717c5cb, in #315, merged on 6th Mar 2016 - meaning it first appeared in a release in 1.26.0.3 (on 19th Sep 2016). FYI, see `DiskInsert()` after the comment `Check if image is being used by the other drive...`.

I still need to check the other issues...

**Comment by sicklittlemonkey** [comment] 2017-05-28 21:43
Great, thanks Tom.

**Comment by tomcw** [comment] 2017-06-03 16:14
Testing @TommyGH 's observations against AppleWin 1.26.2.4 (release):

1. Can't reproduce.
2. Can repro this one - a minor bug.
3. Can repro this one - a minor bug.
4. Can repro this one - a minor bug.

Bugs 2,3,4 should be fixed.

**Closed** 2017-06-03 17:22 UTC
