### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by phed001** [AppleWin/AppleWin#560] opened 2018-06-06 18:42 UTC
I have the following suggestion:
Allow custom speed to be entered, not selected by a slider. (Can be limited to a speed)
Allow slot connection cards to be freely re-aranged, or
slot 1: printer card (e.g. Grappler+)
slot 2: Super Serial Card or Z80 CPM card or mouse card
slot aux: memory card (e.g. RamWorks) with option/ability to add up to 2048 KB
slot 4: Z80 CPM card or mouse card or sound card
slot 5: Z80 CPM card or mouse card or sound card or memory card with option/ability to add up to 2048 KB
slot 6: Disk ][ card
slot 7: hard disk card

(If no sound card is selected, then all the sound should be sent to the PC speaker)

**Comment by tomcw** [comment] 2018-06-07 20:41
> Allow slot connection cards to be freely re-aranged

See #155.

> slot aux: memory card (e.g. RamWorks) with option/ability to add up to 2048 KB

Already supported, but only from the command line (not the GUI Configuration). From the AppleWin.chm help file:

> -r <number of pages>
> Emulate a RAMworks III card with 1 to 127 pages (each page is 64K, giving a max of 8MB)

> slot 4: Z80 CPM card or mouse card or sound card
>slot 6: Disk ][ card
> slot 7: hard disk card

These are already supported.

>(If no sound card is selected, then all the sound should be sent to the PC speaker)

This is already supported, but IIRC sounds terrible on modern Windows OS's (Win7, Win10), so I'll probably remove this.

So the new things you are suggesting are:
- Allow custom speed to be entered, not selected by a slider. (Can be limited to a speed)
- printer card (e.g. Grappler+)

I'll create new issues for these, and then close this a duplicate of #155.

**Comment by tomcw** [comment] 2018-06-07 20:46
Closing as duplicate

**Closed by tomcw** 2018-06-07 20:46 UTC
Labels: Peripheral, UI, duplicate, enhancement
