### ISSUE TITLE
Curse of Azure Bonds and Pool of Radiance crashes during character creation

### ISSUE THREAD

**Issue by markbradley1982** [AppleWin/AppleWin#582] opened 2018-09-13 11:34 UTC
During character creation Curse of the Azure Bonds and Pool of Radiance both crash after it asks you to change from your save disk to disk 1. It's impossible to play both games if you want to create brand new characters.
 
Disk images available here for testing

http://www.virtualapple.org/curseoftheazurebondsdisk.html

**Comment by tomcw** [comment] 2018-09-13 17:28
Hi Mark - what version of AppleWin are you running?

**Comment by markbradley1982** [comment] 2018-09-14 00:52
Hi thanks for getting back to me. I am using AppleWin 1.27.0.0

**Comment by tomcw** [comment] 2018-09-15 09:47
A quick triage...

For AppleWin 1.13.1, 1.25.0.4, 1.27.8.0: the game crashes in similar ways. But AiPC 0.1.41.2 works fine.

In the disk save routine at $BA00, at $BA4C is a JSR $FCA8 (WAIT).
At the point this is executed, BSR is enabled (for both r/w), and the code at $FCA8 is 0x00, ie. BRK. Which is the cause of the game crash.
If I NOP-out this JSR FCA8, then the game save appears to work.

Perhaps a very subtle bug in the BSR emulation? More triage required...

**Comment by markbradley1982** [comment] 2018-09-15 09:55
Is AiPC ApplePC for DOS?

When should I NOP out of JSR FCA8? Before I save my game? It's my first time using an Assembler based debugger.

**Comment by tomcw** [comment] 2018-09-15 10:29
Mark - these are just my notes so far on investigating this. I don't recommend NOP'ing out the JSR - it's certainly not a solution, just an observation.

AiPC is another Apple II emulator available here: https://github.com/sosaria7/appleinpc

**Comment by tomcw** [comment] 2018-09-17 20:29
At "INSERT CURSE SAVE DISK, PRESS A KEY", I set a VS breakpoint on $C08n accesses:

```
898a: lda c089	; disable HRAMRD
898d: lda c089
8991: lda c08b	; enable HRAMRD
8994: lda c08b

898a: lda c089	; disable HRAMRD
898d: lda c089
8991: lda c08b	; enable HRAMRD
8994: lda c08b
```

NB. The repeat accesses just keep HRAMRD in the same state.

I checked the BSR emulation ($C08n accesses) against Sather, and it all looks correct.

**Comment by tomcw** [comment] 2018-09-17 21:10
I tried GSport v0.31 with mixed success:
- save character worked without crashing
- but I then couldn't pick this character (it was in the list, but couldn't be selected)
- on trying to create another new character, at "INPUT THE CHARACTER'S NAME", I just get white squares when I type, and nothing is accepted. So I'm stuck at this point in the game.

**Comment by tomcw** [comment] 2018-09-20 21:29
AFAICT this is a bug, and my current feeling is that it's disk II related.

**Comment by tomcw** [comment] 2018-09-22 11:07
I tried the latest MAME 0.201b (29 Aug 2018): mame64 apple2ee -sl6 diskiing:
- Using .zip (read-only) for boot & disk1; the save .dsk is extracted from the zip so that it's r/w.
- This results in: SAVE FAILED

(The save .dsk  does get modified - Windows updates the file's 'Modified' attribute to today, a compare with the original from the .zip image shows them to be binary identical.)

NB. There are already 12 characters on this save .dsk, **so maybe this is the maximum?**

I then went on to CREATE SAVE DISK (overwriting the original save disk) and successfully saved my character.

**Comment by tomcw** [comment] 2018-09-22 19:48
OK, here's the problem:

In the disk's `ReadSector` routine at $BA00, it starts with the following code (perhaps to check if the disk is spun-up yet?):

```
	LDY #8
BA10: LDA DATASTROBE		; 4
	JSR B433 / RTS		; 6+6 cycles
	CMP DATASTROBE
	BNE BA1E
	DEY
	BNE BA10
BA1E:
```

So there are 8 attempts to detect a change in the disk II's data latch with a 16 cycle (high nibble) delay. If no difference is detected (after 8 tries) then at $BA4C it will `JSR WAIT`.

The code makes no attempt to set the LC / $C08n switches, sometimes ROM is switches in and sometimes the LC is. At $FCA8, the LC contains BRK (and hence the reported crash). My guess is that this "error" code path wasn't well tested and it's a bug in the original game.

Back to this 16us disk nibble reading code: AppleWin's disk II data latch support is pretty crude and just returns the next nibble whenever the latch is read. But (for the save disk, which is largely empty) there's a high chance that the disk will be in a position where there are 16 identical nibbles, resulting in this crash. In fact after a CREATE SAVE DISK, the next nibbles to read are the 128x gap1 sync FF's. So this consistently crashes.

I've hacked something into AppleWin just to prove this is the issue. Now I can CREATE SAVE DISK and save characters to it. I can also save characters to the original save disk - resulting in 13 characters on the disk (so I don't know why this isn't working with MAME). In fact if I keep saving characters it fails for the 17th: MAX 16 CHARACTERS PER DISK.

What I need is a more elegant fix for AppleWin than what I currently have.

**Comment by tomcw** [comment] 2018-09-29 20:35
There's a fix for this in PR #586.
If the Disk II read latch accesses are very close (<=6 cycles) then just return a partial nibble to the latch.

---

Originally I had <=16 cycles, but the fragment of code above is missing a prior $C0EC access. The complete code is:

```
BA00: ; Entrypoint
	(4F8) = 5
	LDA WRITEPROT		; rw mode = read
	LDA DATASTROBE
	LDY #8
BA10:	LDA DATASTROBE		; 4
	JSR B433 / RTS		; 6+6 cycles
	CMP DATASTROBE		; 4
	BNE BA1E
	DEY
	BNE BA10
```

So the 2 access either side of the `LDY #$8` have a gap of 6 cycles.

I tested with AZTEC (originally the <=16 cycles, then with <=6 cycles) to understand any performance impact.
### To my surprise AZTEC actually loaded 3x faster!

So I dug into this to understand why...

AZTEC uses DOS 3.3, and at $BD34 is a similar routine to the above one (from Curse of the Azure Bonds):

```
BD34: ; SAMESLOT
; Enter read mode and read with delays to see if disk
; is spinning. (Ref: Beneath Apple DOS)

read partial. pc=BD3C
BD34:	LDA $C08E,X
	LDA $C08C,X	; 4
	LDY #8		; 2
BD3C:	LDA $C08C,X		; TOTAL=6 ; 4
	PHA		; 3
	PLA		; 4
	PHA		; 3
	PLA		; 4
	STX	$5F8	; 4
	CMP $C08C,X	; TOTAL = 22
	BNE BD4E
	DEY
	BNE BD3C
BD4E:	PHP
	...
BD74:
; Select appropriate drive...
; If drive was on, branch to $BD90.
; Wait for capacitor to discharge using MSWAIT
; subroutine at $BA00. (Ref: Beneath Apple DOS)

	; Pre: A=floppy-latch or floating bus!
	; Delay ~= 6*25600 + 12800 = 166400 = 0.166s
BD85:	LDY #7
	JSR BA00	; Arm move delay subroutine (Ref: Beneath Apple DOS)
			; Delay of: A * 100usec
	DEY
	BNE BD87
```

Looking at the calls to $BA00 before and after this partial nibble read fix:
(caller address, count)

```
Before:
+ [0]	(0xb9d7,0x0000009e)
+ [1]	(0xb9e3,0x0000009e)
+ [2]	(0xb9ea,0x00000013)
+ [3]	(0xbd87,0x0000051d)
$BA00 call count = 0x0000066c

After:
+ [0]	(0xb9d7,0x0000009e)
+ [1]	(0xb9e3,0x0000009e)
+ [2]	(0xb9ea,0x00000013)
$BA00 call count = 0x0000014f
```

So introducing this partial nibble read completely eradicates these huge delays at $BD85.

**Comment by tomcw** [comment] 2018-09-29 20:48
For AZTEC, I did some analysis of partial nibble reads for both <=16 cycles and <=6 cycles:

w/o partial reads:
- Read count = 866303, partial read count = 0

w/partial reads: (nReadCycleDiff <= 16)
- Read count = 866047, partial read count = 780547 (9276 from C6nn firmware)

w/partial reads: (nReadCycleDiff <= 6)
- Read count = 866047, partial read count = 188

But even with these 780,547 extra reads the AZTEC loading was still 3x, as the spin-up delays still massively dominated.

NB. On my PC, the AppleWin benchmark gives me a 217MHz pure CPU rating. These extra reads will equate to: LDA $C08C,X; BPL -5; or 7 cycles. And 7*780,547 / 217M = 0.0251s = 25.1ms.

**Comment by sicklittlemonkey** [comment] 2018-09-30 21:38
Hi Tom.

Great analysis!

Apologies for still not being in a position to contribute - especially in
this area.
I first discovered SAMESLOT back in the 90's, and I remember surprising
Colin Klipsch (who wrote Catakig) with it.

In fact because performance was so limited back then, I used a simple
trick, something like:
if ((read_counter & 0xF) == 0) latch = 0

Basically, an invalid nibble every 16th nibble will fool SAMESLOT.

Cheers,
Nick.

**Comment by tomcw** [comment] 2018-10-02 20:17
Yep, that's a neat way of achieving a similar thing when you aren't cycle counting.

Back then you'd really notice these big delays (SAMESLOT), as the emulation was so slow - now, we miss them because the emulation is so fast!

**Comment by tomcw** [comment] 2018-10-02 20:32
Here's a complete look at AZTEC (ie. DOS 3.3) and how varying the threshold affects partial reads & boot time. (On my desktop P: Win7-64, AMD Phenom II dual-core @3ghz)

**Observation:** Taking an extra 2.5M extra partial latch reads only increases boot time by ~100ms!
So it may not even be worth the special case for "threshold <= 6" and instead just use the accurate value of "threshold <= 31".

Threshold (cycles) | full reads | partial reads | boot time (ms)
-|-|-|-
00 | 866303 | 0 | 2059
01 | 866304 | 0 | 2059
02 | 866304 | 0 | 2075
03 | 866304 | 0 | 2075
04 | 866304 | 0 | 2060
05 | 866304 | 0 | 2059
06 | 866048 | 188 | 655
07 | 866048 | 188 | 671
08 | 866048 | 188 | 655
09 | 866048 | 188 | 656
10 | 866048 | 254 | 687
11 | 866048 | 17922 | 671
12 | 866048 | 29057 | 686
13 | 866048 | 29057 | 671
14 | 866048 | 29057 | 671
15 | 866048 | 32512 | 733
16 | 866048 | 780548 | 718
17 | 866048 | 780868 | 718
18 | 866048 | 798536 | 733
19 | 866048 | 809671 | 733
20 | 866048 | 809671 | 718
21 | 866048 | 811621 | 717
22 | 866048 | 819375 | 702
23 | 866048 | 1567599 | 748
24 | 866048 | 1567930 | 749
25 | 866048 | 1594154 | 748
26 | 866048 | 1669231 | 780
27 | 866048 | 1670166 | 764
28 | 866030 | 1675471 | 749
29 | 866030 | 1683225 | 765
30 | 866030 | 2431619 | 827
31 | 866030 | 2431950 | 780

Where:
- Threshold (cycles) = Gap between Disk II read latch accesses, such that AppleWin will output a partial nibble.
- Full reads = number of full nibble reads (ie. gap between accesses > threshold).
- Partial reads = number of partial nibble reads (ie. gap between accesses <= threshold).
- Boot time (msecs) = time from Apple II machine power cycle to "PRESS ANY KEY" message.

**Comment by tomcw** [comment] 2018-10-02 20:41
And a similar look at Phasor (music card disk) booting (ProDOS 1.1.1) to the "Select an Option:" message:

**Observation:** There's no SAMESLOT for ProDOS, and so increasing the threshold just increases the number of partial latch reads (~600K in this case) resulting in a slightly longer boot time (~40ms in this case).

Threshold | full reads | partial reads | boot time (ms)
-|-|-|-
00 | 250301 | 0 | 3058
01 | 250302 | 0 | 3089
02 | 250302 | 0 | 3073
03 | 250302 | 0 | 3089
04 | 250302 | 0 | 3089
05 | 250302 | 0 | 3073
06 | 250302 | 0 | 3042
07 | 250302 | 0 | 3104
08 | 250302 | 0 | 3058
09 | 250302 | 0 | 3073
10 | 250302 | 318 | 3089
11 | 250302 | 1279 | 3073
12 | 250302 | 5825 | 3105
13 | 250302 | 5825 | 3088
14 | 250302 | 5825 | 3089
15 | 250302 | 43463 | 3088
16 | 250302 | 182007 | 3073
17 | 250302 | 182445 | 3089
18 | 250302 | 184188 | 3088
19 | 250302 | 188734 | 3105
20 | 250302 | 188734 | 3089
21 | 250302 | 189203 | 3089
22 | 250302 | 226842 | 3104
23 | 250289 | 366530 | 3089
24 | 250289 | 367038 | 3121
25 | 250289 | 368469 | 3105
26 | 250289 | 383157 | 3089
27 | 250289 | 389691 | 3105
28 | 250289 | 409649 | 3104
29 | 250289 | 476130 | 3105
30 | 250289 | 615715 | 3120
31 | 250289 | 616223 | 3104

**Comment by tomcw** [comment] 2018-10-02 21:18
I've tested with both Curse of the Azure Bonds & Pool of Radiance.
I've also tested with a variety of DOS 3.3, ProDOS and custom loaders.
Merged PR #586.

**Comment by tomcw** [comment] 2018-10-02 21:44
Hi Mark,
Here's a new build of [AppleWin 1.27.9.0](https://github.com/AppleWin/AppleWin/releases/download/v1.27.9.0/AppleWin1.27.9.0.zip) which fixes this issue.
Can you test it?

**Comment by markbradley1982** [comment] 2018-10-09 07:49
Hi Tom,

I'm traveling at the moment, but I'll test it soon. Thanks again for the assistance!

**Comment by tomcw** [comment] 2018-10-09 21:01
No problem, whenever you get time.
I'll close this bug once you've confirmed it's fixed.

**Comment by tomcw** [comment] 2018-12-08 14:00
Hi Mark - I'm closing this issue. Please re-open if you disagree.
btw. use [AppleWin 1.27.13.0](https://github.com/AppleWin/AppleWin/releases/download/v1.27.13/AppleWin1.27.13.0.zip), as there was a regression introduced at 1.27.9 (for Ultima V when using Authentic Disk Speed).

**Closed by tomcw** 2018-12-08 14:00 UTC
Labels: bug

**Comment by tomcw** [comment] 2019-12-04 23:49
>Observation: Taking an extra 2.5M extra partial latch reads only increases boot time by ~100ms!
So it may not even be worth the special case for "threshold <= 6" and instead just use the accurate value of "threshold <= 31".

See #733 for a case where "threshold <= 31" doesn't work.
