### ISSUE TITLE
Disk 2 won't work from command line

### ISSUE THREAD

**Issue by mcfilmmakers** [AppleWin/AppleWin#981] opened 2021-09-02 21:57 UTC
I try to run AppleWin with several commandline variations but none will load a rom into the disk 2 slot, however, loading into disk 1 does work:

-f -d2 "full/path/to/file" -d1 "full/path/to/file"
-f -s5d2 "full/path/to/file" -d1 "full/path/to/file"
-f --s5 diskii -s5d2 "full/path/to/file" -d1 "full/path/to/file"

Either I'm doing something wrong or the command line isn't working...

**Comment by tomcw** [comment] 2021-09-03 14:34
What AppleWin version are you using?

**Comment by mcfilmmakers** [comment] 2021-09-03 14:36
I'm using 1.30.4.0

**Comment by tomcw** [comment] 2021-09-04 09:53
Hmm, I'm having trouble reproducing this.

If possible can you attach:
1) an AppleWin.log
   - eg. `applewin.exe -log -f -d2 "full/path/to/file" -d1 "full/path/to/file"`
2) your Registry keys for AppleWin
   - `Windows key + R` ->  "regedit"
   - Navigate to "HKEY_CURRENT_USER\Software\AppleWin"
   - Right click -> Export

**Comment by mcfilmmakers** [comment] 2021-09-04 17:06
*** Logging started: 9/4/2021 1:02:55 PM
Unsupported arg: "E:\LaunchBox\Games\Apple II\221b baker street (1986)(datasoft)(side a)[cr digital gang].do
CmdLine: -log -f -d2 "E:\Launchbox\Games\Apple II\221b baker street (1986)(datasoft)(side b)[cr digital gang].do" -d1  "E:\LaunchBox\Games\Apple II\221b baker street (1986)(datasoft)(side a)[cr digital gang].do"
g_sStartDir = E:\LaunchBox\Emulators\AppleWin\
AppleWin version: 1.30.4.0
Init: CoInitializeEx(), hr=0x00000000
Init: SysClk_InitTimer(), res=1
Init: GdiSetBatchLimit()
Init: GetProgramDirectory()
RegDeleteValue(.bin) failed (0x00000005)
RegSetValue(.do) failed (0x00000005)
RegSetValue(.dsk) failed (0x00000005)
RegSetValue(.nib) failed (0x00000005)
RegSetValue(.po) failed (0x00000005)
RegSetValue(.woz) failed (0x00000005)
RegSetValue(DiskImage) failed (0x00000005)
RegSetValue(DiskImage\DefaultIcon) failed (0x00000005)
RegSetValue(DiskImage\shell\open\command) failed (0x00000005)
RegSetValue(DiskImage\shell\open\ddeexec) failed (0x00000005)
RegSetValue(DiskImage\shell\open\ddeexec\application) failed (0x00000005)
RegSetValue(DiskImage\shell\open\ddeexec\topic) failed (0x00000005)
Init: RegisterExtensions()
Init: FrameRegisterClass()
Main: LoadConfiguration()
Main: DebugInitialize()
Main: JoyInitialize()
Main: VideoInitialize()
Main: FrameCreateWindow() - pre
WM_CREATE
WM_CREATE: CreateGdiObjects()
0: Primary Sound Driver - 
1: Speakers (High Definition Audio Device) - {0.0.0.00000000}.{95c35bbf-f301-4db7-8854-100dc9603ce2}
2: Digital Audio (S/PDIF) (High Definition Audio Device) - {0.0.0.00000000}.{be5290a1-89f6-4803-bd06-6718aab1ac98}
3: ASUS VC239 (NVIDIA High Definition Audio) - {0.0.0.00000000}.{fd92a815-c7bf-4596-87e3-5af939dcdb7c}
Number of sound devices = 4
DSCreate succeeded for sound device #0
WM_CREATE: DSInit()
DirectInputInit: g_bDisableDirectInput=0
DirectInputUninit
DirectInputInit: DirectInputUninit()
DirectInputInit: DirectInput8Create(), hr=0x00000000
DirectInputInit: CreateDevice(), hr=0x00000000
DirectInputInit: SetDataFormat(), hr=0x00000000
DirectInputInit: SetCooperativeLevel(), hr=0x00000000
DirectInputInit: Acquire(), hr=0x00000000
DirectInputInit: SetTimer(), id=0x00000001
WM_CREATE: DIMouse::DirectInputInit()
MB_Initialize: g_bDisableDirectSound=0, g_bDisableDirectSoundMockingboard=0
MB_Initialize: AY8910_InitAll()
MB_DSInit
MB_DSInit: DSGetSoundBuffer(), hr=0x00000000
MB_DSInit: DSZeroVoiceBuffer(), res=1
MB_DSInit: SetVolume(), hr=0x00000000
SSI263::DSInit: DSGetSoundBuffer(), hr=0x00000000
SSI263::DSInit: SetVolume(), hr=0x00000000
SSI263::DSInit: DSGetSoundBuffer(), hr=0x00000000
SSI263::DSInit: SetVolume(), hr=0x00000000
SSI263::DSInit: DSGetSoundBuffer(), hr=0x00000000
SSI263::DSInit: SetVolume(), hr=0x00000000
SSI263::DSInit: DSGetSoundBuffer(), hr=0x00000000
SSI263::DSInit: SetVolume(), hr=0x00000000
MB_Initialize: MB_DSInit(), g_bMBAvailable=1
MB_Initialize: MB_Reset()
WM_CREATE: MB_Initialize()
Spkr Config: soundtype = 1 (WAVE)
Spkr_DSInit: SetVolume(0) res = 00000000
Spkr_DSInit: GetCurrentPosition kludge (00000000)
Spkr_DSInit(), res=1
WM_CREATE: SpkrInitialize()
WM_CREATE: DragAcceptFiles()
WM_CREATE (done)
FrameCreateWindow: SetTimer(), id=0x00000002
Main: FrameCreateWindow() - post
Init: S6, DoDiskInsert(D1), res=1
Init: S6, DoDiskInsert(D2), res=1
Main: MemInitialize()
Main: RegisterHotKeys()
Main: HookFilterForKeyboard()
Main: DiskReset()
Main: HDDReset()
LoadLibrary WPCAP.DLL failed!
Main: tfe_init()
Main: Snapshot_Startup()
Main: EnterMessageLoop()




Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\AppleWin]

[HKEY_CURRENT_USER\SOFTWARE\AppleWin\CurrentVersion]

[HKEY_CURRENT_USER\SOFTWARE\AppleWin\CurrentVersion\Configuration]
"Printer Filename"="E:\\LaunchBox\\Emulators\\AppleWin\\Printer.txt"
"Version"="1.30.4.0"
"Video Emulation"="2"
"Video Style"="0"
"Monochrome Color"="12632256"
"Video Refresh Rate"="2"
"Serial Port Name"=""
"Custom Speed"="0"
"Emulation Speed"="10"

[HKEY_CURRENT_USER\SOFTWARE\AppleWin\CurrentVersion\Configuration\Slot 5]
"Card type"="1"
"Last Disk Image 2"=""

[HKEY_CURRENT_USER\SOFTWARE\AppleWin\CurrentVersion\Configuration\Slot 6]
"Card type"="1"
"Last Disk Image 1"=""
"Last Disk Image 2"="E:\\Launchbox\\Games\\Apple II\\221b baker street (1986)(datasoft)(side b)[cr digital gang].do"

[HKEY_CURRENT_USER\SOFTWARE\AppleWin\CurrentVersion\Preferences]
"Last Disk Image 1"="willy byte in the digital dimension (4am crack) side a.dsk"
"Starting Directory"="E:\\LaunchBox\\Games\\Apple II\\"
"Window X-Position"="342"
"Window Y-Position"="111"
"Last Disk Image 2"="willy byte in the digital dimension (4am crack) side b - boot.dsk"

<a href="https://ibb.co/10tRNHR"><img src="https://i.ibb.co/10tRNHR/Capture.png" alt="Capture" border="0"></a>

**Comment by mcfilmmakers** [comment] 2021-09-04 17:08
Note that if I remove the -d2 argument, Applewin launches without issue with either of the 2 disks in d1 so something about -d2 is broken somewhere.

**Comment by tomcw** [comment] 2021-09-05 10:23
Certainly there's an issue if you _were_ to add extra spaces between the command line arguments. But clearly this isn't the case for you, since I can see your command line ("CmdLine") from the .log output - and it is fine.

Continuing to investigate...

**Comment by mcfilmmakers** [comment] 2021-09-05 15:24
So here's what I just discovered: 
If I do this: 
-log -f -d1 %romfile% -d2 "E:\Launchbox\Games\Apple II\221b baker street (1986)(datasoft)(side b)[cr digital gang].do" 

Then Applewin launches properly with both disks in both drives. %romfile% tells launchbox to inject the game's rom filepath at that location instead of at the end of the command line.

However this:
-log -f -d2 "E:\Launchbox\Games\Apple II\221b baker street (1986)(datasoft)(side b)[cr digital gang].do" -d1
with nothing after -d1 (Launchbox automatically injects the full rom filepath (as shown in the log file shared earlier) at the end of the command line.) I get the error message like shown earlier. Clicking Yes, Applewin loads disk 1 but not disk 2.

However this:
-log -f -d2 "E:\Launchbox\Games\Apple II\221b baker street (1986)(datasoft)(side b)[cr digital gang].do" -d1 %romfile%,
also won't insert disk 2, but does insert disk 1 and I do not get the error message.

So, for some reason, the command HAS to have -d1 first and -d2 second in order to function. Perhaps you could explore making it so that they can be in any order to avoid the problem.

**Comment by tomcw** [comment] 2021-09-06 20:23
I found another minor bug: if the -d2 image can't be opened, then AppleWin doesn't report this as an error. It just fails to put a disk in that 2nd drive.

----

btw, I thought perhaps it was a command line length issue, since this is 258 chars:
```
E:\LaunchBox\Emulators\AppleWin\applewin.exe -log -f -d2 "E:\Launchbox\Games\Apple II\221b baker street (1986)(datasoft)(side b)[cr digital gang].do" -d1 "E:\LaunchBox\Games\Apple II\221b baker street (1986)(datasoft)(side a)[cr digital gang].do"
```
But a comment on StackOverflow [here](https://stackoverflow.com/questions/3205027/maximum-length-of-command-line-string), says:
>On computers running Microsoft Windows XP or later, the maximum length of the string that you can use at the command prompt is 8191 characters.
>> This only applies to the programs actually run through the command prompt (per the question). Shortcuts (.lnk) are limited to 260 characters, CreateProcess to 32767, and ShellExecute to about 2048. According to Raymond Chen's article on the subject

And the [Microsoft docs about WinMain](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-winmain) say nothing about limitations.

**Comment by mcfilmmakers** [comment] 2021-09-06 20:54
Well it definitely isn't a character length issue because -d1 followed by -d2 works but -d2 followed by -d1 doesn't. Both commands are the same length.

**Comment by tomcw** [comment] 2021-09-10 13:42
Commit comment for 35b8376 ref'd wrong issue! (Should be this one)

**Comment by tomcw** [comment] 2021-09-10 14:31
@mcfilmmakers - I still can't reproduce this issue.

I've recreated folder paths & image names that match yours, and from a command line (regardless of -d1 or -d2 order) and both images always load correctly.

```
D:\LaunchBox\Emulators\AppleWin\applewin.exe -log -f -d2 "D:\Launchbox\Games\Apple II\221b baker street (1986)(datasoft)(side b)[cr digital gang].do" -d1 "D:\LaunchBox\Games\Apple II\221b baker street (1986)(datasoft)(side a)[cr digital gang].do"

D:\LaunchBox\Emulators\AppleWin\applewin.exe -log -f -d1 "D:\Launchbox\Games\Apple II\221b baker street (1986)(datasoft)(side a)[cr digital gang].do" -d2 "D:\LaunchBox\Games\Apple II\221b baker street (1986)(datasoft)(side b)[cr digital gang].do"
```

Does this problem occur with previous version of AppleWin too? Or just 1.30.4.0?

**Comment by tomcw** [comment] 2021-09-10 15:04
I looked on the LaunchBox forums, and there's this thread that looks useful:
https://forums.launchbox-app.com/topic/62972-applewin-how-to-correctly-import-it-in-lb/?tab=comments#comment-390479

The advice (for multi-disk games) seems to be the same as what you are saying (above) **that works for you**, eg:
>So here's what I just discovered:
>If I do this:
>-log -f -d1 %romfile% -d2 "E:\Launchbox\Games\Apple II\221b baker street (1986)(datasoft)(side b)[cr digital gang].do"
>
>Then Applewin launches properly with both disks in both drives. %romfile% tells launchbox to inject the game's rom filepath at that location instead of at the end of the command line.

My suggestion is that to just stick to this working format, ie. -d1 %romfile% -d2 full/path/to/rom
(Since I can't repro this issue, then I suspect LaunchBox is the problem.)

**Comment by tomcw** [comment] 2021-09-10 19:44
I've just tried LaunchBox v11.17 (free version).

For me, all 3 combinations that you describe above in https://github.com/AppleWin/AppleWin/issues/981#issuecomment-913174875 work!

EG...  (and note this is the release version of AppleWin 1.30.4.0 - so identical to the one you are using)
![image](https://user-images.githubusercontent.com/6696896/132908416-8a699e2f-922c-41e3-b8f9-a11c5c942d35.png)

NB, that the "sample command" erroneously(?) shows `"FULL\PATH\TO\ROM\FILE"` at the end:
```
AppleWin.exe -log -d2 "D:\Launchbox\Games\Apple II\221b baker street (1986)(datasoft)(side b)[cr digital gang].do" -d1 %romfile% "FULL\PATH\TO\ROM\FILE"
```

...now if there were a bug in LaunchBox where it passed this argument at the end twice, then that might explain some of the issues you've been having.

**Comment by mcfilmmakers** [comment] 2021-09-14 02:21
SOrry I haven't responded sooner, I was away for the weekend. I can't say I've come across a need for two disks in other systems so I can't offer any insight into whether it's a launchbox issue but clearly, it must be so I'll let them know my experience and hopefully they will sort it out.

Thank you so much for taking the time to look into it!

**Comment by tomcw** [comment] 2021-09-18 10:29
No problem. I'm going to close this now (as invalid), but if you get more info or evidence to indicate that AppleWin is at fault, then we can reopen this.

**Closed by tomcw** 2021-09-18 10:29 UTC
