### ISSUE TITLE
AppleWin 1.28.0 disk image loading

### ISSUE THREAD

**Issue by MarcoVerpelli** [AppleWin/AppleWin#618] opened 2019-01-23 12:58 UTC
Hi,

Last AppleWin version do not (auto)mount a floppy disk image in S6,D1 when I select it with a double click.
Windows 10 Home 1803 32 bits

Marco

**Comment by tomcw** [comment] 2019-01-23 14:50
FTR, this works OK on Win7 (VAIO laptop), but I need to check on Win10.

**Comment by MarcoVerpelli** [comment] 2019-01-23 15:13
What I tried to do for now is:
make a backup and then delete the registry keys and launch AppleWin, the keys are recreated but still does not work.

[HKEY_CLASSES_ROOT\DiskImage\shell\open\command]
@="\"C:\\Program Files\\AppleWin\\Applewin.exe\" \"%1\""

Marco

**Comment by MarcoVerpelli** [comment] 2019-01-24 10:36
OK, this can be closed.
After a: sfc /scannow and dism /online /cleanup-image /restorehealth is back to work.

Very strange! I clicked on a floppy image, AppleWin started but the image was not mounted.
Do not ask me why, every other file/program association worked normally

TY

Marco

**Comment by tomcw** [comment] 2019-01-24 14:44
>OK, this can be closed.

Closing... if it reoccurs then please re-open.
(And if you discover the cause of the problem, then add a comment here.)

**Closed by tomcw** 2019-01-24 14:44 UTC
