### ISSUE TITLE
Trace files are too large, inconsistent spacing

### ISSUE THREAD

**Issue by gmontag451** [AppleWin/AppleWin#957] opened 2021-05-22 17:31 UTC
Tracing a file's execution to a text file is incredibly helpful when debugging. But trace files can quickly grow to an unmanageable size. Notepad, Excel, etc. freeze up or bog down when opening them. There are third-party apps which can break them up into smaller chunks, but it would be more convenient to have this done on the fly as they're being created.

Also, it would be nice if every line were consistently laid out. It seems that the status flags take up differing amounts of space depending on their state. I often use Excel to compare two executions, and it's difficult writing formulas to handle every change in the spacing of data.

Keep up the great work!

**Comment by tomcw** [comment] 2021-05-23 14:16
>Notepad, Excel, etc. freeze up or bog down when opening them. 

I really would **not** recommend Notepad - it's just a _very simple_ app based on the default Windows edit control, so isn't designed for large text manipulation. Try [Notepad++](https://notepad-plus-plus.org/) or [baretail](http://www.baremetalsoft.com/baretail/index.php), to name but two good alternatives.

>Also, it would be nice if every line were consistently laid out.

I'm not seeing any inconsistency with status flags, eg: [test.log](https://github.com/AppleWin/AppleWin/files/6528216/test.log)
Can you attach an example of the inconsistency you are seeing.

**Comment by gmontag451** [comment] 2021-05-23 23:07
I'll try those out, thanks! I don't have any traces saved, but I'll come back if it happens again.
I just ran this trace, and something weird happened, but I can't recreate it.... the flags section consists of strange characters, maybe I chose an incorrect option?
(the ...'s are mine, shortening the log)
[weird trace.log](https://github.com/AppleWin/AppleWin/files/6529058/weird.trace.log)

**Comment by sicklittlemonkey** [comment] 2021-05-24 05:30
The trace output format was changed almost one year to the day, so you're
running an old version. Try a newer build.

I did mean to add some kind of filter, but never got around to it. A regex
would be nice ...

Cheers,
Nick.

**Comment by tomcw** [comment] 2021-10-31 12:03
Closing as invalid, since we couldn't reproduce the "flags section consists of strange characters" issue + also they were using an old version (so perhaps if there was a bug it's fixed now).

**Closed by tomcw** 2021-10-31 12:03 UTC
Labels: invalid, Debugger
