### ISSUE TITLE
No sound under Win 10

### ISSUE THREAD

**Issue by Mclaneinc** [AppleWin/AppleWin#1159] opened 2023-01-02 14:27 UTC
I read the older reports and I know sound worked fine under Win 7. Checked and changed the config numerous times, no change, checked my sound blaster was working and the right device was set. All other emulators of various machines work fine. Not a bleep from Applewin?

Log created and added...Any idea's please?

I even cleared the registry key..Still the same.

I keep my machine up to date driver wise and virus scan on a regular basis (I use ZoneAlarm with AV)

[AppleWin.log](https://github.com/AppleWin/AppleWin/files/10332116/AppleWin.log)

**Comment by tomcw** [comment] 2023-01-02 14:55
From your log:
>Spkr_DSInit: SetVolume(-4915) res = 00000000

SetVolume() takes values 0(MAX) to -10,000(MIN), so your -4915 value is towards the quieter end of the scale.

You should be able to adjust this value from AppleWin's Configuration->Sound tab:
- Ensure Device = Sound card
- Speaker volume is set towards the **top** of the slide.
![sound2](https://user-images.githubusercontent.com/6696896/210247655-abd10b41-d3db-4480-93d4-3b0c85d39bbf.png)

Otherwise (with AppleWin closed), then edit the `Speaker Volume` key in the Registry:
HKEY_CURRENT_USER\Software\AppleWin\CurrentVersion\Configuration

**Comment by Mclaneinc** [comment] 2023-01-02 15:06
Hi there,

Sadly I'd tried both sliders at the top and bottom (just in case) and still no sound..

From the devices listed in the log, it should be using the one marked as Speakers and not the other two (one is my monitor and the other the optical cable that isn't connected..

**Comment by tomcw** [comment] 2023-01-02 15:16
In the Registry, I set my `Speaker Volume` key to -4915, and started AppleWin.

The Config->Sound tab looked like my screen grab too, but I just got silence from the speaker under emulation.

If I just tweaked the Speaker slide a tiny bit down, then my sound started to work.

**Comment by Mclaneinc** [comment] 2023-01-02 15:23
Still silence here...Be it speaker alone or with mocking bird, same...

**Comment by Mclaneinc** [comment] 2023-01-02 15:39
Just tried a really old version (the last to support Win 2000) and still the same...

**Comment by tomcw** [comment] 2023-01-02 15:40
For my reference, here's a list of Win10 sound-related issues:
- #355
- #716
- #899

In https://github.com/AppleWin/AppleWin/issues/716#issuecomment-549148591, the problem is solved as follows:
>Eureka! Installing the Realtek-specific audio driver supplied by ASUS results in getting the speaker working in AppleWin. Apparently, even though the Microsoft-supplied generic HD Audio driver seems to work with 100% of everything else, AppleWin doesn't like it for some reason.

If possible try a driver update? (otherwise I'm currently out of ideas)

**Comment by Mclaneinc** [comment] 2023-01-02 16:50
Hi Tom,

I found a way to get sound but its a pain, I found that if I routed the sound from my monitor I got sound back, but the quality isn't stunning and I get some dropout (on all software). Weird...

Not sure how it's working that way, I guess it's sending the sound back to the PC on the HDMI cable as this Dell monitor surely hasn't got a sound card in of some type??

Very strange...

**Comment by tomcw** [comment] 2023-01-02 20:34
Can I just check something in your original sound setup (so not via your monitor):

On AppleWin's Config->Sound tab, enable the Mockingboard (or Phasor) card, then boot this .dsk image:
https://github.com/tomcw/Cybernoid/releases/download/v5/Cybernoid.dsk

Does this make any sound? (it should play a tune)

**Comment by Mclaneinc** [comment] 2023-01-03 09:20
Oddly, it does...Yep, on my normal setup it does indeed play a tune.. ???

**Comment by tomcw** [comment] 2023-01-03 09:45
Hmm... so very much like #716, where he said:
>What is more perplexing is that the Mockingboard output works fine. If I start Skyfox, I get music!

I get the impression that after an initial AppleWin install on a _new machine_ then sometimes the Speaker sound (only) can have a problem. (The Speaker uses a different DirectSound ring-buffer to the Mockingboard, which partly explains why there is a difference between them.)

Can you export the Registry key [HKEY_CURRENT_USER\SOFTWARE\AppleWin], and attach the zipped .reg file here?
(As perhaps there's some erroneous value that's confusing AppleWin)

**Comment by Mclaneinc** [comment] 2023-01-03 09:52
[Applewin.zip](https://github.com/AppleWin/AppleWin/files/10335598/Applewin.zip)

There you go, thanks for the help on this..

**Comment by Mclaneinc** [comment] 2023-01-03 10:33
And yes, Skyfox also plays music and I hear hits on the craft in game, and it's launch noise, I don't hear any shooting noise but don't know if I should.

**Comment by tomcw** [comment] 2023-01-03 21:48
I can't reproduce this yet.
I've imported your Registry keys, but it's still working fine for me.

**Comment by Mclaneinc** [comment] 2023-01-04 10:49
I'd leave it be, I can at least hear all noise if I swap to the monitor output. Bit weird but it seems to be a Win 10 thing...

Thanks for all the help

Paul..

**Comment by tomcw** [comment] 2023-01-04 21:46
Okay, well I'm going to leave this issue open, as there's clearly an AppleWin bug since it works with a Mockingboard, but not a speaker.

**Comment by Mclaneinc** [comment] 2023-01-14 13:51
Hi Tom, tried something today, downloaded the realtek universal drivers as apart from my Soundblaster I have an onboard sound card that I thought was off in the bios. Anyway, ran the drivers as a test and now I have sound after the reboot.

Very odd..Oh well, it works and I'm happy now :)

**Comment by tomcw** [comment] 2023-01-14 14:46
That's great to know!

(A random thought: the Speaker uses a mono sound buffer, whereas the Mockingboard uses stereo. Perhaps the original driver has an issue with this mono buffer?)

As you say very odd.
Anyway, thanks for the update.

**Comment by Mclaneinc** [comment] 2023-01-14 14:54
No idea but at least it's a fix, maybe for others too..

Thanks for the work on the emulator Tom, much appreciated..

Paul..

**Comment by audetto** [comment] 2024-01-14 10:41
Why is the speaker not playing the same sound on both channels?

https://github.com/AppleWin/AppleWin/blob/78ee8101d592ee52a872ac6a221ac622cbffe28b/source/Speaker.cpp#L386

**Comment by tomcw** [comment] 2024-01-14 15:52
@audetto - thanks for the check. It was my fault. I've corrected this now.

**Comment by audetto** [comment] 2024-01-14 16:35
Looks good now.

**Comment by tomcw** [comment] 2024-03-23 15:29
Closing, as speaker dual-mono is implemented in [AppleWin 1.30.18.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.18.0).

**Closed by tomcw** 2024-03-23 15:29 UTC
Labels: bug
