### ISSUE TITLE
Command line -d1 fails

### ISSUE THREAD

**Issue by bengarrett** [AppleWin/AppleWin#421] opened 2017-05-15 06:52 UTC
I am using Windows 10 Pro 64-bit. AppleWin works perfectly except for this one CLI issue.

When I try and use the `-d1` argument AppleWin fails to load. But strangely if I use `-d2` it launches as expected with the image in drive 2.

```

*** Logging started: 15/05/2017 4:44:21 PM
CmdLine: -l -d1 "C:\Games\Apple II\04 - Cranston Manor.dsk"
AppleWin version: 1.25.0.3
Init: CoInitializeEx(), hr=0x00000000
Init: SysClk_InitTimer(), res=1
Init: GdiSetBatchLimit()
Init: GetProgramDirectory()
Init: RegisterExtensions()
Init: FrameRegisterClass()
Init: ImageInitialize()
Init: DiskInitialize()
Init: CreateColorMixMap()
Init: DoDiskInsert(D1), res=1
*** Logging started: 15/05/2017 4:46:15 PM
CmdLine: -l -d2 "C:\Games\Apple II\04 - Cranston Manor.dsk"
AppleWin version: 1.25.0.3
Init: CoInitializeEx(), hr=0x00000000
Init: SysClk_InitTimer(), res=1
Init: GdiSetBatchLimit()
Init: GetProgramDirectory()
Init: RegisterExtensions()
Init: FrameRegisterClass()
Init: ImageInitialize()
Init: DiskInitialize()
Init: CreateColorMixMap()
Init: DoDiskInsert(D2), res=1
Main: LoadConfiguration()
Main: DebugInitialize()
Main: JoyInitialize()
Main: MemInitialize()
Main: VideoInitialize()
Main: FrameCreateWindow() - pre
WM_CREATE
WM_CREATE: CreateGdiObjects()
0: Primary Sound Driver - 
1: Speakers (Realtek High Definition Audio) - {0.0.0.00000000}.{b393bb2e-8021-45dc-8691-d1abf634ca8b}
Number of sound devices = 2
DSCreate succeeded for sound device #0
WM_CREATE: DSInit()
DirectInputInit: g_bDisableDirectInput=0
DirectInputUninit
DirectInputInit: DirectInputUninit()
DirectInputInit: DirectInput8Create(), hr=0x00000000
DirectInputInit: CreateDevice(), hr=0x00000000
DirectInputInit: SetDataFormat(), hr=0x00000000
DirectInputInit: SetCooperativeLevel(), hr=0x00000000
DirectInputInit: Acquire(), hr=0x00000000
DirectInputInit: SetTimer(), id=0x00000001
WM_CREATE: DIMouse::DirectInputInit()
MB_Initialize: g_bDisableDirectSound=0, g_bDisableDirectSoundMockingboard=0
MB_Initialize: AY8910_InitAll()
MB_DSInit
```

**Comment by tomcw** [comment] 2017-05-17 22:17
This is a duplicate of #276.
Please us 1.25.0.4 or later.
The current latest stable build is [1.26.1.1](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.1.1)

**Closed by tomcw** 2017-05-17 22:17 UTC
Labels: 1.25.0.3, duplicate
