### ISSUE TITLE
"Illegal Command", and "Ambiguous 2 Commands  DISASM DISK"

### ISSUE THREAD

**Issue by TommyGH** [AppleWin/AppleWin#473] opened 2017-08-19 05:49 UTC
Emulator: 1.26.3.0
Debugger: 2.9.0.8

It seems something is broken worse than before.  I get strange errors when running my debugger script.

My "debug.txt" script file:
[debug.txt](https://github.com/AppleWin/AppleWin/files/1236074/debug.txt)

My "A2_USER1.SYM".
[A2_USER1.SYM (2).txt](https://github.com/AppleWin/AppleWin/files/1236073/A2_USER1.SYM.2.txt)

1. Start AppleWin.exe
2. Boot DOS3.3 disk
3. F7
4. ESC (to "skip")
5. Enter (to display whole console window).
6. RUN DEBUG.TXT

After "Default Path:" is displayed, there is text:

++++++++++++++++++
Illegal Command
Ambiguous 2 Commands:
 DISASM DISK
++++++++++++++++++

Now modify DEBUG.TXT.   Near the end of the file are 2 lines commented out.  Remove the "//" from both lines so that the commands will execute:
ma1 d0d0
mt2 ff0a

And repeat the steps 1 to 6 from above.

The error at the end now changes!?  It looks like more of the script execution is now shown (?)

After "Default Path:" is displayed, there is text:

++++++++++++++++++
Illegal Command
Branch type: 2
colon: ON
Opcodes: ON
Info Target Pointer: OFF
Opcode spaces: ON
Target: 3
++++++++++++++++++

**Comment by TommyGH** [comment] 2017-08-19 05:58
Goodness.  I just did another experiment.
I noticed that after the last commented line in the file I had a "line" with no text.  In other words, I entered the "// R PC RESET" as the last line in my script, pressed the ENTER key, and then saved the file.  I'm using NotePad.exe.
Perhaps AppleWin.exe is having trouble determining the end of the file!? And is processing random stuff?

**Comment by Michaelangel007** [comment] 2017-08-23 14:58
I'll try to take a look at this later today ...

**Comment by Michaelangel007** [comment] 2017-08-24 16:50
Didn't get a chance yesterday ... should today.

**Comment by Michaelangel007** [comment] 2017-08-25 00:08
OK, able to repro.  Investigating ...

**Comment by Michaelangel007** [comment] 2017-08-25 00:12
Caused by this line:

```
disasm COLON  1  // Colon after addresses
```

**Comment by Michaelangel007** [comment] 2017-08-25 00:35
`di` is getting passed into `DebuggerProcessCommand()` causing the `DisplayAmbigiousCommands( 2 )` to be triggered.

**Comment by Michaelangel007** [comment] 2017-08-25 00:52
MemoryTextFile_t::Read() isn't setting null terminator

**Comment by Michaelangel007** [comment] 2017-08-25 01:44
Whoops, closed by mistake.

**Comment by Michaelangel007** [comment] 2017-08-25 01:46
NOTE: Need to merge #480 before we can pump debugger version & update docs/Debugger_Changelog.txt

**Comment by tomcw** [comment] 2018-01-06 16:28
Bumped debugger version (2.9.0.12) & updated docs/Debugger_Changelog.txt.

**Closed by tomcw** 2018-01-06 16:28 UTC
Labels: Debugger, bug
