### ISSUE TITLE
emulate Mac IIe card's DLGR colour palette?

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#1258] opened 2023-11-22 16:45 UTC
Feature request.
The Mac IIe card had a bug where the DLGR aux bank does not use the shifted values for the colours.
i.e., it requires the same values be written to both main and aux in order to show the same colour.
Having that support would really help me to debug and support the card in TR with proper colours.

**Comment by burniouf** [comment] 2023-11-22 21:48
Noticed this bug in DLGR, are you sure same in DHGR ?

**Comment by peterferrie** [comment] 2023-11-23 00:29
My mistake.  DLGR, indeed.  I have edited to correct it.

**Comment by tomcw** [comment] 2023-11-23 07:48
Hi Peter,
Sure, this sounds quite straightforward. A few things...

1. Can you share a photo of an image from the Mac IIe card so I know if it's the aux or main value that is not shifted. (Or some other description eg. writing 0x0N to 00/400 and 01/400 shows colours X then Y in the top-left when in DLGR mode.)

2. A command line switch is easiest for me to add this, but what your preference? EG, maybe an in-app Config toggle suits your workflow better?

Thanks.

**Comment by peterferrie** [comment] 2023-11-24 22:42
Hi Tom,

https://github.com/a2-4am/4cade/issues/518
has a picture of the issue.  As I understand it, the aux values should match the main values.
A command-line switch is fine.  I don't need a UI for it.
Thanks.

**Comment by peterferrie** [comment] 2023-11-25 06:10
I don't need a toggle, either.  I would run two AppleWins side by side, one enabled and one not, because that would faster for me to compare.

**Comment by burniouf** [comment] 2023-11-25 08:28
Maybe a good idea should be to also add the ROM, because some detection code may use $FBDD value to identify "regular //e" or "LC card"

https://mirrors.apple2.org.za/apple.cabi.net/FAQs.and.INFO/A2.TECH.NOTES.ETC/A2.CLASSIC.TNTS/a2misc007(1).htm

**Comment by tomcw** [comment] 2023-11-25 10:20
If I had the ROM then I could just add a new machine type ("Apple IIe Card for Macintosh LC")... but I can't find the ROM having searched the usual places (asimov, IA).

**Comment by burniouf** [comment] 2023-11-25 12:07
https://lowendmac.com/2018/apple-iie-card-a-tool-for-getting-macs-into-schools/

Seems 64k ROMs and a SECOND ($C02B ?) aux RAM bank = TOTAL 256k RAM space in the card

**Comment by peterferrie** [comment] 2023-11-25 22:06
I'm only interested in the colours, so that I can know when the wrong
values are written and then write the right ones. :-)

**Comment by burniouf** [comment] 2023-11-25 22:14
to solve your issue, i do like this : 
i use those Translate Tables for anything except LC Card...
*--------------------------------------
PALETTE.MAIN	.HS 00.02.04.06.08.0A.0C.0E
				.HS 01.03.05.07.09.0B.0D.0F
PALETTE.AUX		.HS 00.01.02.03.04.05.06.07
				.HS 08.09.0A.0B.0C.0D.0E.0F

for LC Card i use ONLY  PALETTE.MAIN for both banks

**Comment by peterferrie** [comment] 2023-11-25 22:58
Thanks, but it's other people's code that I'm looking to fix, so I don't
know for sure where all of the palettes are stored.

**Comment by tomcw** [comment] 2023-11-26 18:05
Hi @peterferrie,
I've added a new cmd line switch (-mac-lc-card-dlgr) to enable this buggy mode.

Before:
![dgr-colorbars_000000000](https://github.com/AppleWin/AppleWin/assets/6696896/dd730083-a52d-4848-8e6d-0dd77fd01b07)

And with the mode enabled:
![dgr-colorbars_000000001](https://github.com/AppleWin/AppleWin/assets/6696896/466efb93-9c24-47b0-9161-5a5b25e2a150)

NB. This switch only has an effect when in either "Color (Composite Idealized)" and "RGB Card/Monitor" video modes... so not for any of the NTSC TV/Monitor modes.

**Comment by tomcw** [comment] 2023-11-26 18:25
@peterferrie - I've put a pre-release [here](https://github.com/AppleWin/AppleWin/releases/download/v1.30.16.0/AppleWin1.30.16.0.zip).

NB. "pre-release" as I've not run my full regression suite against it yet.

**Comment by peterferrie** [comment] 2023-11-27 06:00
Super!  Thanks Tom, it does exactly what I needed.

**Comment by tomcw** [comment] 2023-11-27 18:43
Great! - I will close this.

>NB. "pre-release" as I've not run my full regression suite against it yet.

Tested now, so promoted it to a full release.

**Closed by tomcw** 2023-11-27 18:43 UTC
Labels: enhancement

**Comment by peterferrie** [comment] 2023-11-28 21:05
The originating TR issue is also fixed now!  Thanks again.
