### ISSUE TITLE
FRQ - Support for 3.5" media

### ISSUE THREAD

**Issue by TedThompson** [AppleWin/AppleWin#584] opened 2018-09-20 05:57 UTC
I've seen evidence of //e at least and perhaps earlier having 3.5" drives attached (400k?) it would be nice to mount 800kb disks to the floppy drive rather then as a HDD.

**Comment by tomcw** [comment] 2018-09-20 21:18
Duplicate of #104. Closing.

**Closed by tomcw** 2018-09-20 21:18 UTC
Labels: duplicate, enhancement
