### ISSUE TITLE
Oo-Topos can't boot in enhanced IIe mode (1.26.3.6)

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#532] opened 2018-01-28 02:21 UTC
source: https://archive.org/details/OoTopos4amCrack
The external Slot 3 ROM behvaiour is somehow not proper, and ProDOS fails to unmap it again.  Then when the game attempts to initialise the internal card, it crashes instead.

**Comment by tomcw** [comment] 2018-01-28 11:47
I can't reproduce this (using 1.26.3.6, in Enhanced IIe mode, slots 4,5,7 empty).

I've tried both _"Oo-Topos (4am crack) side B - boot.dsk"_ and _"00playable.dsk"_(*): both boot to the title screen ("(S)tandard or (D)ouble hi-res graphics?", I select "D"), then if I just press a key (so don't flip the disk) it loads to the start of the game ("You are in a prison cell...").

Do you have any cards inserted into any slots?

Perhaps you can attach a save-state (.aws.yaml) file, so I can see you configuration.

(*) btw. there is a 1 byte binary difference between these 2 .dsk images: at offset 0xED95, the "4am crack" has 0xEB, whereas "00playable" has 0xB2 at this offset.

**Comment by tomcw** [comment] 2018-01-28 12:03
>(*) btw. there is a 1 byte binary difference between these 2 .dsk images: at offset 0xED95, the "4am crack" has 0xEB, whereas "00playable" has 0xB2 at this offset.

I got it the wrong way round:

At offset 0xED95, the "4am crack" has 0xB2, whereas "00playable" has 0xEB at this offset.

And from "Oo-Topos (4am crack).txt", the cracked version should have 0xB2, so I will ignore the "00playable.dsk".

**Comment by peterferrie** [comment] 2018-01-28 21:39
Ah, it's triggered by the debugger.
Enter the debugger from the AppleWin splash screen, and then "gg".
Selecting either option at the prompt will show the bug.

Booting without debugger interaction works correctly.

**Comment by tomcw** [comment] 2018-01-29 23:18
Thanks for clarifying this.

Initial findings:
FF38: JMP C314
At this point:
- For gg: SLOTC3ROM=1
- For g: SLOTC3ROM=0

Current working theory is that because gg mode doesn't support the floating bus (#477) then this may be confusing some card detection code... except that running in full speed (outside of the debugger) works fine.

**Comment by tomcw** [comment] 2018-01-30 22:05
>except that running in full speed (outside of the debugger) works fine.

No it doesn't.

At full-speed (debugger active or not), then the following reads a constant floating-bus value 256 times, so fails to restore the internal C3 ROM:
```
2104: 
 sta $c00b	; SETSLOTC3ROM
 lda $c30c
 ldx #0
210c:
  cmp $c30c
  bne $211b
  dex
  bne $210c
 lda $c30c
 cmp #$88
 bne $211e
211b:
 sta $c00a	; SETINTC3ROM
211e:
 jsr $bf00
 .data c5 ae 21
 bne $2174
```

**Comment by tomcw** [comment] 2018-01-30 22:07
For the full-speed (non-debugger) case then selecting (S)tandard will fail the following ProDOS MLI call, and execute this BRK:
```
1c0a:
 lda #0
 sta $1c60
 lda #$61
 sta $1c61
 jsr $bf00
 .data cc 64 1c
 bne $1c1d
 rts
1c1d:
 brk
```

BRK will vector to $C3FA (but slot ROM is enabled) so just starts executing floating-bus data. At full-speed this is just a _constant value_ ($A0 $00 / LDY #$0), so eventually ends up at $C600, which causes a reboot.

**Comment by tomcw** [comment] 2018-01-30 22:09
For the full-speed (debugger, eg. gg) case then the debugger will break on the first attempt to execute floating-bus data. As above this is when at $FF38, the code JMPs to $C314 (ie. the entrypoint for XFER).

**Comment by tomcw** [comment] 2018-01-30 22:27
Hi Peter,

This (just like #508) is the current "spec" for this `gg` cmd, which again is not a great user experience.

I have an idea (comment in #519) to update the video scanner h/v position whenever floating-bus data is required.

**Comment by tomcw** [comment] 2018-02-02 21:14
Fixed, so closing.

**Closed by tomcw** 2018-02-02 21:14 UTC
Labels: enhancement

**Comment by tomcw** [comment] 2018-02-07 21:09
@peterferrie - FYI, from AppleWin 1.27, the `gg` (and other things that enable full-speed) now allow the emulated Apple II to correctly read the floating-bus. So for Oo-Topos, Canyon Climber and other games that use II+ video sync.

**Comment by peterferrie** [comment] 2018-02-07 21:35
Thanks Tom.  I can confirm success.

**Comment by tomcw** [comment] 2018-02-07 22:23
Good stuff - thanks for confirming.
