### ISSUE TITLE
[AppleWin 1.26a] Faint clicking every few seconds 

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#262] opened 2015-01-16 22:43 UTC
> (Audio) faint clicking every few seconds (caused by starving the Mockingboard??)

I've tried to reproduce this, but without success.
What .dsk image are you using?

Does this happen in both Debug and Release?
- With the extra processing required for NTSC, then Debug could be running close to max'ing out a CPU core.

Is there anything else running on your PC which could be starving AppleWin of execution time on CPU?

Have you tried disabling Mockingboard from the Config?

Finally, in Visual Studio's Output pane look for output like this:

```
197411.449: [Submit]    PC=0000271E, WC=00003174, Diff=00000A56, Off=00003056, NS=00000090 xxx
197411.465: [MBUpdt]    PC=00005C04, WC=000070B0, Diff=000014AC, Off=00006764, NS=000002EC xxx
197424.366: [Submit]    PC=00000704, WC=0000115A, Diff=00000A56, Off=00000D2A, NS=0000002D xxx
197424.382: [Submit]    PC=00000A76, WC=000014CC, Diff=00000A56, Off=000013AE, NS=0000007C xxx
197424.382: [MBUpdt]    PC=00001BD0, WC=0000307C, Diff=000014AC, Off=00002870, NS=0000033C xxx
```

These messages tend to mean that the sound ring-buffers (Speaker or Mockingboard) aren't getting filled quickly enough.

You'll also get these message when you click & drag the window around.

**Comment by tomcw** [comment] 2015-01-18 21:49
Another reason for the faint clicks could be too many calls to OutputDebugString() - this would only be for a **Debug build**.

For example: unrelated to NTSC, I get this faint clicking when running Fantavision with the Mousecard enabled (Debug build), because of OutputDebugString().

**Comment by Michaelangel007** [comment] 2015-01-18 22:06
Hey Tom

Sorry haven't been able to provide anyone details just yet -- I will next week.

It is happening with a release build too which I thought was really strange.

So it looks like we are starving the audio buffer then?

**Comment by tomcw** [comment] 2015-01-18 22:33
>So it looks like we are starving the audio buffer then?

Yes, it sounds like it. What is the clock speed of your CPU?

Give me details of how to repro this, when you get time next week.

**Comment by Michaelangel007** [comment] 2015-01-18 22:48
i7 4770K o/c'd to 4040 MHz

**Comment by tomcw** [comment] 2015-01-19 21:34
OK, so it's not a low spec CPU then!

**Comment by tomcw** [comment] 2016-10-16 20:43
Hi Michael,
Is this still occurring for you (eg. with 1.26.0.6)?

**Comment by tomcw** [comment] 2017-05-11 20:49
Hi Michael,
This was raised >2 years ago, but (AFAIK) it's never been reproduced by you.
Can I close as 'invalid'? (We can always reopen if you get this problem again)

**Comment by Michaelangel007** [comment] 2017-05-13 14:45
Let me try to take another look at it this weekend.

if you don't hear from by Monday, then go ahead and close it.

**Comment by Michaelangel007** [comment] 2017-05-15 16:23
Tom, go ahead and close this since this is a regression.

I don't get the warm-and-fuzzy feelings when a bug is magically "fixed" -- so I'll continue to `git bisect` this offline and try to track down when this:

* started
* stopped

**Closed** 2017-05-15 16:23 UTC
Labels: bug
