### ISSUE TITLE
When using color tv option the top line is scrunched

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#865] opened 2020-11-11 11:29 UTC
When using color tv option the top line in HGR is scrunched. You can see what I mean if you look at the "S" in SCORE in StarBlazer. The top part the "S" in SCORE seems to be drawn with 2 rows of sub-pixels. The bottom parts of the "S" is drawn with 3 sub-pixels.

But if you look at the bottom "S" in "STAR CRAFT", both the top and bottom of the "S" are the same size.

The same applies if taking a screenshot in any mode.

**Comment by tomcw** [comment] 2020-11-11 14:35
Sounds like a duplicate of #650.
See https://github.com/AppleWin/AppleWin/issues/650#issuecomment-529022576

**Comment by tomcw** [comment] 2020-11-12 10:27
Closing duplicate.

**Closed by tomcw** 2020-11-12 10:27 UTC
Labels: duplicate
