### ISSUE TITLE
Crusade In Europe 

### ISSUE THREAD

**Issue by bdjphotoman590** [AppleWin/AppleWin#430] opened 2017-06-30 03:36 UTC
Hi, I never did get the save game feature to work on the Apple IIc.  When I try to save it says to insert blank disk and then takes you to another screen and then you can return to the game.  Is there anyway to create or fix the save game feature so we can play the long scenarios?  This goes for Decision in the Desert and Conflict In Vietnam as well.  Dont know about Nato Commander.  Thanks, bdjphotoman590

**Comment by tomcw** [comment] 2017-06-30 21:10
Perhaps a better (more generic save) solution is to use AppleWin's save-states.

You can also check the "Save state on exit" box (Configuration -> Advanced tab). This will both save (on exit) and reload (on AppleWin start-up). Press F2 at the AppleWin logo screen to restart from where you left off.

**Comment by tomcw** [comment] 2017-06-30 22:19
I was able to use the (S)ave and (L)oad operations from the game.

From the AppleWin.chm help (Disks and Disk Images -> Creating Disk Images):
_To create a new disk image, all you have to do is tell AppleWin to use an image file which doesn't already exist and the emulator will automatically create a new image file._

I inserted a blank disk when asked to. I then typed "99" to initialize the disk. At this point I could save the game to an empty slot. And I could then re-load this saved game later on.

**Comment by bdjphotoman590** [comment] 2017-07-08 04:01
I tried to create a blank disk for Decision In The Desert by using the help and double clicking on the create disk image tab.  Nothing happened.  I tried to print the tab and again nothing happened.  I tried to drag it to a word pad and still nothing happened.   I am on Windows 7 if that helps.  
For the first option, I followed the directions and the save game sent me back to the beginning of the game  to choose the type of game to play, scenario, etc.
Derek.

**Comment by sicklittlemonkey** [comment] 2017-07-08 15:44
Reading CHM files on Windows 7:
https://stackoverflow.com/questions/11438634/opening-a-chm-file-produces-navigation-to-the-webpage-was-canceled

Cheers,
Nick.

**Comment by bdjphotoman590** [comment] 2017-07-09 08:09
OK, got the disk made and everything.  Saved the game.  But, when do I load the game to bring the saved game up.  Sorry if this sounds too simple, I am not as computer smart as I use to be.
Derek.

**Comment by sicklittlemonkey** [comment] 2017-07-10 04:42
> OK, got the disk made and everything.

Well done.

> Saved the game.

Great.

> But, when do I load the game to bring the saved game up.

What? You can save the AppleWin state at any time.

Then you can load AppleWin's state at any time and continue playing.

That's an alternative to getting the game's save game feature working.

Or if you want to show us something, wait till it goes wrong, save the
AppleWin state and send it to us.

Cheers,
Nick.

**Comment by peterferrie** [comment] 2017-08-30 22:44
the save game window requires that you select one of the slots in which to save the game state.
to load the game afterwards, you have to start a scenario.

**Comment by tomcw** [comment] 2017-09-07 20:44
Closing, since this is confirmed as working (and IMO save-state is a better alternative).

**Closed by tomcw** 2017-09-07 20:44 UTC
Labels: question
