### ISSUE TITLE
The OpenApple + <Return> problem

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#556] opened 2018-05-21 05:50 UTC
The Applewin OpenApple + \<Return\> problem? Seems this key combo from the //e doesn't work in AppleWin. The documentation confirms it.

Is there any workaround to send that keycombo to a program? If not, maybe a special key sequence or mouse/joystick sequence or one-time trigger could be devised that would allow it. There are some programs that do make use of that keycombo. The one I found the other day was part of a setup procedure for TIMEOUT, and the illegal keycombo is supposed to let you add a prodos prefix to a list.

**Comment by tomcw** [comment] 2018-05-21 12:10
Similar to #145 (for Open-Apple + ESC).

One workaround is to set "Joystick 1" to "Keyboard (num pad)", and then use the Numeric Pad's '0' and '.' for Open/Closed Apple respectively (instead of the left/right ALT keys).

**Comment by tomcw** [comment] 2018-05-21 20:54
And similar to the question you asked in #448 :-)

**Comment by tomcw** [comment] 2018-05-21 21:10
And you were the one that originally request ALT+ENTER to go full-screen, here: #198!

**Comment by landloafer** [comment] 2018-05-23 02:40
I am on Win7. I heard "Ding" windows' warning beat when ever I hold Alt+anykey.

**Comment by tomcw** [comment] 2018-05-26 16:39
A heavy-weight (system global) workaround, but you can make Default Beep make no sound:

![image](https://user-images.githubusercontent.com/6696896/40578424-9ee1b0c8-610b-11e8-9ab6-1df4b5ab1af6.png)

**Comment by tomcw** [comment] 2018-05-26 17:05
OK, I found a way to programmatically suppress the Default Beep.

**Comment by tomcw** [comment] 2018-05-27 10:06
As Michael said in #145, the solution is to use `SetWindowsHookEx()`.

I've committed an initial implementation that suppresses ALT+TAB, ALT+ESC and CTRL+ESC *globally* within the system. So when AppleWin is running then these system key-combos don't do anything for whichever Window or application that has focus. Quitting AppleWin restores the default Windows behaviour for these key combos.

to do:
- [ ] Update the other VS solutions to include this new HookFilter DLL project
- [ ] Add a cmd line switch to inhibit this system key suppression and update help.
- [ ] Check that AppleWin can now receive ALT+ESC, ie. the virtual machine can get OpenApple+ESC (#145)
- [ ] Check that AppleWin can now receive ALT+TAB, ie. the virtual machine can get OpenApple+TAB
- [ ] Add a cmd line switch to inhibit ALT+ENTER from toggling full-screen.

**Comment by tomcw** [comment] 2018-05-28 15:13
Simple test:

```
5 PR#3
10 B0 = 49249 : REM $C061 / Button#0
20 B1 = B0 + 1
30 K = 49152 : REM $C000
40 AKD = K + 16
100  PRINT  PEEK (B0), PEEK (B1), PEEK (K), PEEK (AKD)
110  GOTO 100
```

**Comment by tomcw** [comment] 2018-05-28 16:33
Commit 6b53add - extend hook filter for ALT+SPACE, PostMessage() and special AKD support.

**Comment by Keatah** [comment] 2018-05-28 18:55
Ohh dear.. I work with so many emulators it gets hard to remember what I asked for.

**Comment by tomcw** [comment] 2018-05-29 22:10
Not to worry - it's prompted me to take a closer look at this.

**Comment by tomcw** [comment] 2018-06-16 10:01
I noticed that the save-state is always saving 'Last Key' as 0x00, so I'll roll the fix up into this issue.

**Comment by tomcw** [comment] 2018-06-16 10:41
Added regression test for system keys, AKD and -alt-enter=open-apple-enter: https://github.com/AppleWin/AppleWin-Test/commit/12cbcd81cbba1ea68b8448e24a9276be53d15750

**Comment by tomcw** [comment] 2018-06-16 10:43
Closing this as all work complete. I'll add a comment here when there's a new build to try.

**Closed by tomcw** 2018-06-16 10:43 UTC
Labels: bug

**Comment by tomcw** [comment] 2018-06-24 09:29
@Keatah: I've released a new 1.27.5 version [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.27.5.0).

You'll need to use a new command-line switch to enable OpenApple + Return (as this key combination defaults to full-screen toggle). See the help or release note.

**Comment by sicklittlemonkey** [comment] 2018-07-28 23:13
Not being able to use Alt-Tab in Windows when AppleWin is open cramps my style!? ; - )

What's the plan going forward?

**Comment by tomcw** [comment] 2018-07-29 09:46
There is a cmd line switch (-no-hook-system-key) to suppress the keyboard hook filter, but this is no good once you've started AppleWin (and forgotten to use the switch).

Some ideas:

1. When AppleWin loses the focus, then unhook the keyboard filter (and vice versa: re-hook when AppleWin gets the focus again).
   - but when you ALT+TAB back into AppleWin, then you'll be stuck again!
2. Provide a GUI Config option to enable/disable this keyboard hook behaviour
    - default to allowing ALT+TAB to switch apps (ie. standard Windows behaviour)

**Comment by sicklittlemonkey** [comment] 2018-07-29 11:18
Yeah for (2) - this should be a GUI option that I'd personally never want to enable. ; - )

I suppose it might make more sense in full screen, in the sense of turning your PC into an Apple II. But again I personally wouldn't use it even then unless there was some particular case I was testing.

**Comment by tomcw** [comment] 2018-07-29 21:07
Well, I'd rather not add extra GUI options, especially since there's no actual request for ALT+TAB... so perhaps the best approach is only support it via a cmd-line switch.

Therefore what about:
- default: keyboard hook filter enabled, but it only suppresses ALT+ESC (#145) and ALT+SPACE (no user requests)
- new switch for hook filter to suppress ALT+TAB (no user requests)
- new switch for hook filter to suppress ALT GR's fake LCONTROL message (#558, no user request)
  - NB. suppressing this fake LCONTROL seems to prevent international keyboards from being able to type certain keys
  - But (when RMENU / ALT GR is pressed) then posting WM_CHAR, seems to be fine, but just won't work in the ALT GR + CONTROL +\<key\> case. Again no one's asking for this, so currently no big deal.

Why even bother with the new switches to suppress ALT+TAB and the fake LCONTROL? Well I've done the work now, and if in the future there's a request to support these then they will be available.

**Comment by sicklittlemonkey** [comment] 2018-07-30 04:38
Ok, sounds good. The new behaviour just surprised me, and someone else on FB: "Yikes, it captures Alt-Tab! *rolls back*"! ; - )

Cheers,
Nick.

**Comment by tomcw** [comment] 2018-08-06 21:11
Hi Nick,
FYI, there's a new 1.27.7 release [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.27.7.0) with the hooked ALT+TAB **reverted**.
