### ISSUE TITLE
Disk ][ MC3470 noise emulation

### ISSUE THREAD

**Issue by sicklittlemonkey** [AppleWin/AppleWin#695] opened 2019-09-24 11:51 UTC
John had to mod an image of Taipan to boot on AppleWin. His posts in the Apple II Enthusiasts FB group are here:
Original: https://www.facebook.com/groups/5251478676/permalink/10158955388273677/
Modified: https://www.facebook.com/groups/5251478676/permalink/10158957588948677/

"I revised to the .woz to work around a compatibility issue with AppleWin."

"It appears that AppleWin has an issue with MC3470 noise emulation. So, I went into the flux editor again and reduced a flux gap in order to prevent the noise from injecting a bit and desynchronizing an address field. The original disk uses the gap as a copy protection method."

"Considering that the original disk wouldn't boot, it needed to be touched anyway. But, the actual data that comes in through the disk latch is exactly the same. I removed some 0 bits which just makes the proper nibble show up 12 microseconds sooner."

I've attached the original that had a different fix applied (it wouldn't boot on real hardware) but this hasn't had the AppleWin fix applied and should fail on AppleWin.
[Taipan.woz.zip](https://github.com/AppleWin/AppleWin/files/3649797/Taipan.woz.zip)

**Comment by tomcw** [comment] 2019-09-24 15:03
Hi Nick - thanks for raising this (and a very interesting video by John showing how he fixed the damaged .a2r image).

When I follow your link it takes me to the FB page, but not John's post (in fact it's nothing to do with John / Taipan etc). Can you attach a zip of the non-working .woz, and I'll take a look?

**Comment by tomcw** [comment] 2019-09-25 14:48
Thanks Nick - that fails at T28 (at the game's title page).

**Comment by tomcw** [comment] 2019-09-28 21:09
Hi John / @kerthunk,

I've been looking at this original Taipan.woz image, but can't figure it out.
Can you let me know where you made this edit...?

> So, I went into the flux editor again and reduced a flux gap in order to prevent the noise from injecting a bit and desynchronizing an address field. The original disk uses the gap as a copy protection method."

All I've been able to deduce is that on T28 (T$1C) it does this:
- read sector $C...$1
  - NB. sector $0 is all FF's - unused in DOS 3.2.
- cycle=00ED8BF5: $c0e8 / motor off (DOS 3.2, after reading final sector $1)
  - cycle delta =$F42D (62509)
- cycle=00EE8022: $c0e9 / motor on
  - cycle delta = $A9E1A = $2A786 bit-cells. NB. Track's bit-length=C706 => 3.4 revolutions!
- cycle=00F91E3C: STA $c0ed / reset LSS: PC=$A52
  - cycle delta = $1F9 = $7E bit-cells.
- cycle=00F92035: LDA $c0ee / rw mode: read. PC = $D1E
- And any value with bit7 set allows the game to boot, otherwise it hangs on the title screen (but at the 6502 level it eventually hits a BRK, vectors to ROM, then hits BRK, ad infinitum...)

Sather defines $c0ed/$c0ee as: (Table 9.2)
- Sequencer function = **check state of write protect switch & init sequencer for writing**
  - NB. since it's a write to $c0ed, then the write protect is not read to QA (bit7), so this just resets the Sequencer (LSS).

Apple doesn't emulate the LSS, so just treats these operations _individually_ as:
- reset LSS (ie. init some WOZ image emulation state)
- set read mode & return the data latch

But I tested MAME and microM8 emulators, by repeatedly doing the LDA at $D1E, and replacing the next opcode with JMP $D1E, eg:
```
$d1e: lda ($50),y  ; ($50)=$EE, $(51)=$C0, Y=0
      jmp $d1e
```

Both return a fixed value, and not a changing data latch (eg. if I were read $c0ec). So as the Sequencer isn't set to "READ sequencing" function, then I guess the other emulators are correct in returning a fixed value... **but what is this fixed value?**

In fact MAME (0.211b or 0.214b) doesn't work with either the original or modified Taipan.woz. It just returns 0x00 at $D1E.
And microM8 (1.0.0.0?) works with both, It return 0xFF at $D1E.

**Comment by sicklittlemonkey** [comment] 2019-09-29 13:16
That code looks like it's just checking for write-protect.

Cheers,
Nick.

**Comment by kerthunk** [comment] 2019-09-29 15:30
The patch I made was on track 0. It was failing to load one of the sectors due to a gap before the address prologue. Noise was consistently being injected into there and prevented initial boot up due to a desynchronized address field (at least in the version of AppleWin that I was using). I removed that gap and it booted right up. I didn't have to muck around with T28 at all.

**Comment by tomcw** [comment] 2019-09-29 19:06
Interesting points from you both!

**John:** I've never had any issue with Taipan track-0 using AppleWin, but I'll do some deeper analysis around the noise emulation on this track. NB. the only thing I found was when `(head_window & 0x0f) == 0` then I currently return `rand()&1`, when I should probably bias it so that roughly 30% are 1 bits (as per your WOZ 2.0 spec).

AppleWin 1.29.0 and 1.29.1 both work with the game's T28 code; since for $C0EE reads they would just return the _previous_ data latch value (which always had bit7=1).

But at AppleWin 1.29.2, I changed all even disk I/O reads to return the _current_ latch (ie. running bits through my "sequencer" code from the last even access to this one access).

**Nick:** I think you may be right, but it's a very well hidden (very obfuscated) check for write-protect:
```
  sta ($7D),y  ; ($7D)=$ED, $(7E)=$C0, Y=0, A=0
  ; ~500 cycles, including setting up next $50 and $51 values.
  lda $(50),y  ; ($50)=$EE, $(51)=$C0, Y=0
```

AppleWin currently only loads write-protect into QA (bit7) on an I/O read... so a small fix required here.

**Comment by tomcw** [comment] 2019-09-30 22:05
Nick, in 31f7e7296b97e788d0e1fcf31c6ea9ba4cbfdb17 I have:
- added support for loading write-protect state into QA on a **write** to $C08D,X
- track the state of the Sequencer Function, and only enable reading when in the 'Enable read sequencing' state ($C08C,X & $C08E,X).

For this last point I then noticed you already have 2 flags for this: `m_floppyWriteMode` and `m_floppyLoadMode`... but the latter is commented out with your comment... :-)
>// for efficiency this is not used; it's extremely unlikely to affect emulation (nickw)

We've never needed this before, but now .woz images are enforcing much stricter disk emulation.

**Comment by sicklittlemonkey** [comment] 2019-10-01 04:42
Hi Tom.

Yeah, I'm sure you've already seen this, but if you look at Understanding
the Apple IIe Figure 9.11 on page 9-20, you'll see that Read/Write splits
the sequencer behaviour into two halves (top and bottom), and then
Shift/Load splits it into 4 quadrants (left and right on the bottom, but
arranged differently on the top for Sather's purposes.)

Write protect was already handled in AppleWin in a succinct way that
covered all existing cases. Low-level emulation of the actual sequencer
behaviour in this mode wasn't necessary - perhaps until now. ; - )

After 6 weeks of waiting our shipping has been delivered. I have a desk. I
have a computer. I need to find time to put it together and turn it on ...
I promise I'll try!

Cheers,
Nick.

**Comment by tomcw** [comment] 2019-10-01 08:12
Thanks Nick... and as a carrot, there's .woz image write-support still to do! :-)

**Comment by tomcw** [comment] 2019-10-13 16:14
1.29.3 is release [here ](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.3.0)which fixes the problems I saw with this .woz image.

But I'm leaving it open for now, as I still want to check the track-0 fake bits / noise, as John reported with the original Taipan.woz image.

**Comment by tomcw** [comment] 2019-10-19 16:12
I've compared the original vs modified Taipan images for track-0.
There are only 2 differences:

1. At bit offset 0x1694, the original has an extra nibble (0x80). This is after the LSS has sync, and occurs just before the address prologue nibbles 0xD5AAB5 (ie. DOS 3.2). It doesn't matter about the fake bits generated for this nibble, since it's in sync (so 0xD5 will always be read next).

```
Original:
FF(1)FF(4)FE(1)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF   D7   AA   96   FF   FE   AA   AA   80   D5   AA   B5
                                                                                                              ^^
Modified:
FF(1)FF(4)FE(1)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF(2)FF   D7   AA   96   FF   FE   AA   AA   D5   AA   B5

NB. This address prologue is for Vol:FE Trk:00 Sec:00 Chk:FE
```

2. Between address field D5AAB5 / Vol:FE Trk:00 Sec:0B Chk:F5 and the data prologue, a zero sync bit has been removed (reducing the sync bits from 7 to 6):

```
Original:
DE   AA   EB   FF(7)C4   FE   FF(1)FF(1)FF(1)FF(1)FF(1)FF(1)FF(1)FF(1)FF(1)FF(1)D5   AA   AD(1)
               ^^^^
Modified:
DE   AA   EB   FF(6)C4   FE   FF(1)FF(1)FF(1)FF(1)FF(1)FF(1)FF(1)FF(1)FF(1)FF(1)D5   AA   AD(1)
```

There are 10x 9-bit sync bytes (before the D5AAAD data field prologue) which are enough to sync regardless of the noise generated by the FF(7) bitstream.

----

Summary: for both these cases, I can't see a problem.
Also I've tested (10 retries) with AppleWin 1.29.0, 1.29.1 and 1.29.2 - and Taipan booted in all cases.

@kerthunk : I'm just wondering if you recognise the 2 changes listed above? In your Facebook comment you said _"I removed some 0 bits which just makes the proper nibble show up 12 microseconds sooner"_, but the 1st is a 32us change, and the 2nd is only a 4us change.

If you can't remember this now, then I'll just close this issue, since Taipan is booting fine now.

**Comment by tomcw** [comment] 2019-11-18 17:15
I'm going to close this as I wasn't able to reproduce the issue with track-0 and fake bits / noise.

**Closed by tomcw** 2019-11-18 17:15 UTC
Labels: bug
