### ISSUE TITLE
Conflict In Vietnam Game Fail

### ISSUE THREAD

**Issue by bdjphotoman590** [AppleWin/AppleWin#431] opened 2017-06-30 03:38 UTC
Hi, When I use to play Conflict In Vietnam it would get a fatal error in orange on top of the screen with a number and then the game ends.  Usually it meant the disk was bad.  The game in AppleWin has the same problem for all the scenarios.  Thanks, bdjphotoman590

**Comment by tomcw** [comment] 2017-06-30 22:01
Please give the follow information:
- Reproducible steps
- Configuration of your emulated Apple II system (eg. Apple //e type, what cards are plugged in etc). 

Or attach a save-state file (and rename it to be a .txt file so you can attach it to this issue).

**Comment by tomcw** [comment] 2017-06-30 22:03
NB. I am able to run the game in demo mode OK.

**Comment by bdjphotoman590** [comment] 2017-07-08 05:13
OK, I got it to fail.  I can not print screen it for some reason.  I tried everything I know.  I save state file but the file can not be found.  I did it after the error popped up.  I did the Khe Sanh scenario and chose Variant 1.  I dont know when the scenario started but the error occured at 7:30 P.M. January 24, 1968.  It is in orange or red letters on top of the white screen.  It says Fatal Error: 115.  
Derek.

**Comment by bdjphotoman590** [comment] 2017-07-08 05:15
apple iie 1.26.0.6

**Comment by tomcw** [comment] 2017-07-11 21:19
> I can not print screen it for some reason.

AppleWin takes control of the PrintScreen key and creates a .bmp screenshot in the same folder as the .dsk files. EG. It creates a file called: ConflictInVietn_000000000.bmp for me.

**Comment by tomcw** [comment] 2017-07-11 21:28
>I did the Khe Sanh scenario and chose Variant 1.

I let the game run at full-speed (Config->Emulation Speed = Fastest), and got Fatal Error: 112 at 6:30 A.M. January 24, 1968...

![conflictinvietn_000000001](https://user-images.githubusercontent.com/6696896/28091508-ef4b0bba-6687-11e7-8378-d0775b957df2.png)

**Comment by tomcw** [comment] 2017-07-11 21:38
And this time... Fatal Error: 113 at 5:30 A.M. January 25, 1968...

![conflictinvietn_000000002](https://user-images.githubusercontent.com/6696896/28091919-8244cd56-6689-11e7-9242-7703c74498a0.png)

**Comment by tomcw** [comment] 2017-07-11 22:02
Possibly a poor crack?
EG. It appears to work for N turns before giving this fatal error. If you reported this error code (eg. 110-119?) to MicroProse then they'd know that you were running an illegal copy.

**Comment by sicklittlemonkey** [comment] 2017-07-11 22:27
Is this from asimov?

**Comment by tomcw** [comment] 2017-07-12 10:51
Yes, from this mirror:
http://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/strategy/ConflictInVietnam1.dsk
http://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/strategy/ConflictInVietnam2.dsk

NB. There are other versions of the game on asimov that may be different.
And I should check using other emulators (and older AppleWin's) too.

**Comment by sicklittlemonkey** [comment] 2017-07-12 11:19
Yeah, I had a look tonight.

FATAL ERROR is in memory at $
6104 <- this is perhaps a text buffer for printing
6358 <- this is here during play
6781 <- this is here during play / seems to swap in/out

It has a bytecode interpreter at 0096-00B6
96: jump to bytecode address on stack and execute
A0: increment bytecode address and execute
A8: add A to bytecode address and execute
B4: jump to bytecode handler

Some routines jump through the stack with RTS to 0096
Others jump directly to A0 etc

The two copies on Asimov are identical. Both are (not really) "Cracked by
Kristo"
ftp://ftp.apple.asimov.net/pub/apple_II/images/games/strategy/ConflictInVietnam1.dsk
ftp://ftp.apple.asimov.net/pub/apple_II/images/games/strategy/ConflictInVietnam2.dsk

ftp://ftp.apple.asimov.net/pub/apple_II/images/games/strategy/Conflict%20In%20Vietnam%20(1986)(Microprose)%5Bcr%5D(Disk%201%20of%201%20Side%20A).zip
ftp://ftp.apple.asimov.net/pub/apple_II/images/games/strategy/Conflict%20In%20Vietnam%20(1986)(Microprose)%5Bcr%5D(Disk%201%20of%201%20Side%20B).zip

The Hardcore Computist crack doesn't have any effect on the FATAL ERROR

The most likely approach is to:
1. Get an original NIB etc.
2. Boot code trace to see what checks Kristo thought he found and
removed/circumvented.
3. Find later checks for side-effects of earlier checks.
4. And/or in AppleWin BPM the address of the (2nd, 3rd?) FATAL ERROR text
and see if the state can be traced back.

A very involved crack for someone with the time...

Apparently it's on the 'Asimov Want List' mentioned here:
https://groups.google.com/d/msg/comp.sys.apple2/LzEZ7RVTD2A/ftKr1ZmBmtEJ

Cheers,
Nick.

**Comment by tomcw** [comment] 2017-07-12 20:41
FTR, I tried:
- AppleWin 1.25.0.3 and got "Fatal Error: 113"
- AiPC v0.1.41.1 and got "Fatal Error: 115"
- GSport v0.31 (a debug build that I built a year ago) :  freezes (crashes?) as soon as either the game or demo starts. So not GS compatible? Or a GSport bug?

**Comment by tomcw** [comment] 2017-07-12 21:03
Hi Nick,

And searching on cea2, back in 2004:
https://groups.google.com/d/msg/comp.emulators.apple2/_TuFDI9p8No/iHkJJuMft0cJ

## **Asimov Want List**

>>How about a working copy of "Conflict in Vietnam"?

> The one on Asimov hasn't been copied correctly and still keeps some of its
> old protection routines.
>     The program bombs out with a "Fatal Error 115" if you're running the 64k
> game and a "Fatal Eror 111" if you running the 128k game about half way
> through the campaign, before the game ends. You can test this by running the
> game on demonstration mode (computer v. computer), setting your emalator
> speed to maximum, and let it run for a few minutes. The game will have the
> fatal error every time.
>     Incidentely, Crusade in Europe and Decision in the Desert, the other two
> games in the series, do not have this problem and can be played all the way
> through. However, "Silent Service" on Asimov has the same problem. I think
> they were meant to hook you in by letting you play for 30 minutes or so
> (back in the day) before the program turns on you.

**Comment by tomcw** [comment] 2017-07-12 21:15
I can't find any "Conflict in Vietnam" nib and all the (.dsk) images on Asimov are binary identical.
So probably worth throwing down the gauntlet on csa2 or cea2 for someone to crack it properly?

Anyway this isn't an emulation or AppleWin issue so I will close this.

**Comment by bdjphotoman590** [comment] 2017-07-12 21:56
Hi, I found a copy of conflict in Vietnam new in box and have a copy myself.  The new one is on eBay. Please let me know if I can help or if there is any change or new info on this issue. Derek

**Comment by bdjphotoman590** [comment] 2017-07-12 21:59
I may have been a little too fast. That new copy is for IBM PC. I don't know if that makes it no good or good. I am watching it anyway as I am a buyer and seller on eBay. Derek

**Comment by sicklittlemonkey** [comment] 2017-07-13 00:13
Hi Derek.​

When you say you have a copy yourself, what do you mean? You have ...
1) an original (that works), or
2) a copy that isn't cracked (working or not?)
3) a copy this is cracked (working or not?)

Cheers,
Nick.

**Comment by bdjphotoman590** [comment] 2017-07-13 01:27
An original that works, no error but I will play tomorrow and try to get the error. Yes I have a working apple IIc computer.

**Comment by sicklittlemonkey** [comment] 2017-07-13 04:42
So if you already have an original, I'm puzzled as to why you are looking
on eBay.

Anyway, you have a working original - but one day it will stop working. ; -
)

In the long term your best bet is to have someone crack it. There are
various options ...
1) A short term option: If you have a mass storage device for your Apple
//c (Floppy Disk Emu etc) you can easily make a NIB image with this
program: http://www.brutaldeluxe.fr/products/apple2/imfEDDup/index.html
2) The best option for everyone: Send the disk to someone who will image it
to an EDD file. They will then send your original back to you.

Either way, an image can probably be used to make a working copy.

I see that 4am and qkumba recently cracked Microprose's Crusade in Europe,
which has similar protection to Conflict in Vietnam (and Silent Service
etc).
https://twitter.com/a2_4am/status/884789252772548608

Cheers,
Nick.

**Comment by bdjphotoman590** [comment] 2017-07-13 16:20
Oh, I thought you guys needed a copy. The acronym nib means new in box on eBay. May be I misunderstood. I thought you guys would crack it or tell me to send it to the first group of people you were talking about so that it could end up with you guys. Derek.

**Comment by sicklittlemonkey** [comment] 2017-07-13 19:41
Oh, right. Well someone needs a good physical copy to make a disk image
file. Then the file can be sent to whoever to crack.

The ideal type of disk image (EDD) requires extra hardware (an EDD card).
I'm assuming you don't have that ... but from what I'm hearing a NIB image
might be enough.

A NIB image (sorry for the confusing terminology ; - ) is a nibble disk
image. This can be made on an Apple II by you, if you're willing. The
program I linked to earlier (i'm fEDD up) can do it, but the resulting file
is large (228kB) so it needs a large ProDOS volume to write to. Do you have
a hard drive emulator for your //c like BMOW's Floppy Emu?
https://www.bigmessowires.com/floppy-emu/

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment] 2017-07-14 04:15
Hi Derek.

Just to speed up the communcation ...

If you're willing to image your original, can you let me know what Apple II
hardware you have available?

And do you use ADTPro to transfer images to/from your //c etc? I think
there's another way to get the NIB image.

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment] 2017-07-14 20:57
Reopening because qkumba says this problem is only on AppleWin, not in MAME. Will try to verify today.

**Comment by tomcw** [comment] 2017-07-14 21:45
See (far) above - I reproduced on "Apple in PC" (AiPC) too.

**Comment by bdjphotoman590** [comment] 2017-07-15 00:03
Hi I do not have any other parts for the computer except the Apple IIc and the game. No emulator. No program.  But the computer works. The game is used but it still works with no error on the computer.  Is it hard to get or expensive to get? Derek.

**Comment by sicklittlemonkey** [comment] 2017-07-15 00:34
Hi Derek.

If you're willing, it would be great to get a NIB disk image (i.e.
ConflictInVeitnam.nib). Then we can get it cracked. People have wanted this
game for years! ; - )

As I said, one option would be to safely package the disk and send it to
someone in the US to image. (I assume you're in the US, but I'm in NZ, and
Tom is in the UK. We have colleagues in the US though.)

The other way is to use the //c if you can connect it via a serial cable to
a PC or a Mac. You would need to use the ADTPro software:
http://adtpro.sourceforge.net/

For that to work you'll need a serial cable, and an RS-232 serial port. A
PC might or might not have one. A Mac will not have one.

You can buy a serial cable online here:
http://retrofloppy.com/products.html

And if you have a Mac, or a PC without a serial port, you can get a USB to
RS-232 adaptor here:
http://retrofloppy.com/products.html#USBMAC

With this setup you can also transfer more software to your //c. (That site
also sells new blank disks.)
Let me know what you decide, and today I'll verify that my idea for
transferring the .nib image will work.

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment] 2017-07-15 01:19
Thanks Tom. Closing again as I just replicated FATAL ERROR 112 with a beta crack of Crusade in Europe (from 4am) on a ROM 3 IIgs with a CFFA3000. Took 10 mins at 2.8MHz.

For future reference the errors seem to happen around 25-30 mins (at 1 MHz) into the game. (Verified in AppleWin with g_nCumulativeCycles/60,000,000.

**Closed by sicklittlemonkey** 2017-07-15 01:19 UTC
Labels: question

**Comment by sicklittlemonkey** [comment] 2017-07-15 01:53
Derek, I presume you've completed a game Conflict in Vietnam. How long does
it take?

If you leave computer vs computer for 30 or more minutes, how does it end?

I'd like to verify that the FATAL ERROR never happens on the original you
have!

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment] 2017-07-16 11:56
OK, I verified that ADTPro has the ability to make the .nib image. It's
super easy to get up and running.

I forgot to mention the other option for a cable is of course to make one.
I did this years ago. The DIN5 connector for //c serial is the same as the
old (before PS/2) PC keyboard. The wiring is shown here:
http://adtpro.com/connectionsserial.html#DIN5

Cheers,
Nick.

**Comment by TommyGH** [comment] 2017-07-18 06:10
I've begun an examination (bootstrap trace) of the "Cracked" image from Asimov.
I would be interested in the original non-cracked disk image as well.

Perhaps this discussion should really be moved to comp.sys.apple2 or similar discussion board.

I've found the code most interesting, and not sure if there are bugs as a result of a bad crack, but will share this tidbit of odd behavior:

If you press the escape key <Esc> repeatedly while booting, you get the following error message (using AppleWin and AppleII+):

  PROGRAM REQUIRES MINIMUM 64K MEMORY
   AND APPLESOFT ON MOTHERBOARD

Without pressing any keys, it boots normally.

So what happens if you try booting this without "APPLESOFT ON THE MOTHERBOARD" AppleII (original)?  Using *C600 to boot, and not pressing any keys, it just seems to hang badly.  The code is smart enough to know it's not AppleSoft in ROM, and it detects Apple Integer on "the motherboard" and tries to hard restart at E000, but something apparently wasn't set up properly.

Lots of interesting self-modifying code during the boot process is making this a challenge.

Tommy

**Comment by sicklittlemonkey** [comment] 2017-07-18 06:49
FYI, Tommy.

On the weekend Qkumba found a total of 8(!) protection checks on Crusade in
Europe, which is in the same series as CIV.

They are written using this compiler:
http://www.willegal.net/appleii/IBC.html

Hmm, if only we had a decompiler ... ; - )

Funnily enough I saw the error you mention (64K) on another enhanced //e
emulator I work with.

Cheers,
Nick.

**Comment by TommyGH** [comment] 2017-07-18 23:38
Seems like the compiler has a built in "disassembler."  I haven't looked at the doc closely, but I think this documentation refers to the time of compilation:  

INTEGER BASIC COMPILER", Galfo Systems, P 15:

"DISASSEMBLE COMPILED CODE? Answering YES will give
you a disassembled listing of your program in
symbolic GSL (or GSL/6502) code. (see user notes
for an explanation of the disassembled listing)."

**Comment by sicklittlemonkey** [comment] 2017-07-29 00:22
On 15 July 2017 at 12:03, bdjphotoman590 <notifications@github.com> wrote:
> The game is used but it still works with no error on the computer. Is it
hard to get or expensive to get? Derek.

Hi Derek.

Thought I would send one last ping on this.

Yes, the game seems to be hard to get. ; - )

If you can help preserve it please contact me.

Cheers,
Nick.

**Comment by Michaelangel007** [comment] 2017-07-29 01:03
Derek, I'm in the (greater) Seattle area if you need help getting a NIB dump.

**Comment by peterferrie** [comment] 2017-08-30 22:38
and a crack is finally available.

**Comment by sicklittlemonkey** [comment] 2017-08-30 22:51
Nice one! Will you be doing an Epic write-up? ; - )

Cheers,
Nick.

**Comment by peterferrie** [comment] 2017-08-30 23:46
> Nice one! Will you be doing an Epic write-up? ; - )

Done:
https://archive.org/download/ConflictInVietnam128K_4amCrack/Conflict%20in%20Vietnam%20128K%20(4am%20and%20san%20inc%20crack).txt

**Comment by Michaelangel007** [comment] 2017-08-31 00:30
Epic indeed Nick !

Nicely done guys!  15 protection checks.  WOW.

That interleaving of p-code and native code is so wrong.  And that byte-swapping is just down-right nasty.

Make me wonder what other games were using p-code.  Maybe someone is bored enough to start a list? :-)

**Comment by sicklittlemonkey** [comment] 2017-08-31 00:34
Yes, Epic indeed!

Wizardry, of course.

And Peter has cracked EA titles that used a VM too. I'm pretty sure he
could rattle off a list.

Cheers,
Nick.

**Comment by Michaelangel007** [comment] 2017-08-31 00:38
Thanks for that `Asimov Want List` list Nick !

Sad to see `Empire II` and `Empire III` are still on it.  I say sad because I had access to the original `Empire I` and `Empire II` back in the day!  I _really_ wish I knew that these would become collector items one day. :-/

**Comment by tomcw** [comment] 2017-09-07 21:11
>> and a crack is finally available. 15 levels of protection.

>https://archive.org/download/ConflictInVietnam128K_4amCrack/Conflict%20in%20Vietnam%20128K%20(4am%20and%20san%20inc%20crack).txt

An extremely interesting read!

What tools do 4am and qkumba use for cracking... an emulator? Or even an emulator with source code using an attached modern macOS/Windows debugger for faster turn-around & better debug tools? (EG. AppleWin + Visual Studio)

I imagine emulator save-states would be invaluable for progressively getting further through the game to the next protection scheme.

When this issue was first raised, I took a brief look at C-in-V. I hooked the p-code dispatcher by hacking the AppleWin source code within the 6502 code emulation, eg. if 6502.PC == 0xB4 then do some logging.

From my notes:

> Bytecode opcode $5E is interesting. When playing through the whole game (eg. for ~25 realtime minutes) this opcode is only executed a handful of times. The 6502 code to implement this is at $E64. Looking at this code, it does a few odd EOR $C060 (where $C060 is TAPEIN!). Perhaps it's using this as a random number generator? It finishes at `$F59: JMP A0`

**Comment by peterferrie** [comment] 2017-09-07 22:03
>>https://archive.org/download/ConflictInVietnam128K_4amCrack/Conflict%20in%20Vietnam%20128K%20(4am%20and%20san%20inc%20crack).txt
>
> An extremely interesting read!
>
> What tools do 4am and qkumba use for cracking... an emulator? Or even an
> emulator with source code using an attached modern macOS/Windows debugger
> for faster turn-around & better debug tools? (EG. AppleWin + Visual Studio)

In my case, AppleWin or MAME alone for the speed, and real hardware on occasion.
I don't bother with more in-depth debugging.  I haven't really had the
need so far, though BPMR/W support will help a lot.

> I imagine emulator save-states would be invaluable for progressively getting
> further through the game to the next protection scheme.

Yes, it's great for timing-based issues, that I can let the game run a
bit at a time to get closer to the trigger point.

> When this issue was first raised, I took a brief look at C-in-V. I hooked
> the p-code dispatcher by hacking the AppleWin source code within the 6502
> code emulation, eg. if 6502.PC == 0xB4 then do some logging.
>
> From my notes:
>
>> Bytecode opcode $5E is interesting. When playing through the whole game
>> (eg. for ~25 realtime minutes) this opcode is only executed a handful of
>> times. The 6502 code to implement this is at $E64. Looking at this code,
>> it does a few odd EOR $C060 (where $C060 is TAPEIN!). Perhaps it's using
>> this as a random number generator? It finishes at `$F59: JMP A0`

$5E is RND().

**Comment by peterferrie** [comment] 2017-09-07 23:01
> What tools do 4am and qkumba use for cracking... an emulator? Or even an
> emulator with source code using an attached modern macOS/Windows debugger
> for faster turn-around & better debug tools? (EG. AppleWin + Visual
> Studio)

4am uses real hardware for the most part, otherwise OpenEmulator (at
least until I can get .fdi support into MAME).

**Comment by tomcw** [comment] 2017-09-10 09:48
Thanks Peter - it's very insightful to understand what you both are using.

**Comment by bdjphotoman590** [comment] 2017-10-18 22:54
So sorry to get back to this so much later.  Been very busy and unable to get back on.  Just wanted an update.  Is there a version we can download and play and where would it be?  I do not understand all the computer language above.

**Comment by sicklittlemonkey** [comment] 2017-10-18 23:45
Hi Derek.

https://archive.org/details/ConflictInVietnam128K_4amCrack

Cheers,
Nick.

**Comment by bdjphotoman590** [comment] 2017-10-22 02:25
Thank you and it works!  Unfortunately, I may have discovered another issue.  When I go to freeze the game and just close iwin, it should save it and keep it there for next time I open it up.  It gives me 2 errors and the save game is gone.  I will post the errors when i get them again.  Bdj

**Comment by bdjphotoman590** [comment] 2017-10-26 01:42
Finally, didn't just close the error box.  2 errors.  First line is in the grey box around the words.  
Load State
Failed to initialize parser or open file

Save State
Save error
Also, there was a freeze of the game at the end of Scenario 5, Option 2.  I was attacking the NVA supply depot in their Sanctuary, which I was never able to do so before.  And after a few mins, the game froze.  Bdjphotoman.

**Comment by sicklittlemonkey** [comment] 2017-10-26 02:22
Thanks.

Sounds like there are 2 issues.

1. There's an error loading the save state. If you can please attach the
save state to this issue then someone (Tom? : - ) can have a look.

2. The game "froze". Again, if you can save the state when it's frozen, and
attach the state here, we can ask Peter to have a look.

In order to attach the states you might have to create a GitHub account,
zip them up, and add them to a comment.

Cheers,
Nick.

**Comment by bdjphotoman590** [comment] 2017-10-27 01:17
Sorry, remind me how to do a save state again.  
bdj.

**Comment by tomcw** [comment] 2017-10-27 11:40
You can explicitly save the state using F11.
Or you can get AppleWin to auto-save-state on exit and auto-load-state on AppleWin restart: F8 to open the Config, then from the Advanced tab, select "Save State on exit".

**Comment by peterferrie** [comment] 2017-11-08 03:45
Were you playing for real or just watching the demo?
64kb (side A) or 128kb (side B) version?
What was the game date and time when it froze?
