### ISSUE TITLE
Randomly refuses to save when coding in BASIC

### ISSUE THREAD

**Issue by jblack67204** [AppleWin/AppleWin#1034] opened 2022-02-08 15:56 UTC
I've had this happen several times.  I start writing code and it saves fine the first few times.  Then, it hangs, beeps, and gives me a syntax error when I try to save.  I am on the latest version, but still having this issue.  Am I missing something?

**Comment by sicklittlemonkey** [comment] 2022-02-09 00:07
This is unlikely to be an emulation issue.

Also, many details are unclear. Are you programming in Applesoft? Is your
program getting too big?

You could save the AppleWin state when the error occurs and attach it to
this issue.

**Comment by tomcw** [comment] 2022-02-14 20:50
I will close this soon unless more specific info is given.

**Comment by jblack67204** [comment] 2022-02-15 17:56
Yes, its in Applesoft.  

When this happens, it's like it forgets commands.  For example, it will save a couple of times and then when I go to save, it says SYNTAX ERROR.  If I type "Catalog" it says syntax error.  If I reset the emulator, it still doesn't work.  If I close and reopen AppleWin it works, but whatever I was trying to save is lost.  I did notice it seems to happen after I do CTRL-C to stop a program that is in progress.

**Comment by tomcw** [comment] 2022-02-15 19:06
@jblack67204 - as Nick hints, you need to provide a reproducible...

Either provide a .DSK image with step-by-step instructions so we can reproduce this; or provide a save-state (+.DSK image) so that we can inspect this issue at the point where it's failing.

**Comment by tomcw** [comment] 2022-02-26 16:32
Closing, due to lack of info from OP.

**Closed by tomcw** 2022-02-26 16:32 UTC
Labels: invalid, question
