### ISSUE TITLE
WOZ image size calculation

### ISSUE THREAD

**Issue by Udderdude** [AppleWin/AppleWin#1240] opened 2023-06-15 19:58 UTC
WOZ image size calculation doesn't seem to be working right. I have some woz files I generated using a2woz, which are ~905kb each. (No, I don't know why the woz files it generates are so big compared to others). AppleWin seems to think these are 800kb high density disks, however the actual size of the data on these disks is the same as any other 140kb disk. It's just making this assumption based entirely on the file size. I know this because I'm able to use these woz files with Apple //c in MAME, and it works just fine.

**Comment by tomcw** [comment] 2023-06-17 19:39
Hi @Udderdude - can you attach an example here?
(You will have to zip it up first before attaching)

**Comment by Udderdude** [comment] 2023-06-18 11:49
Here it is.
[Apple II System Disk - Disk 1, Side A.zip](https://github.com/AppleWin/AppleWin/files/11781368/Apple.II.System.Disk.-.Disk.1.Side.A.zip)

**Comment by tomcw** [comment] 2023-06-18 14:56
Thanks. I've confirmed this fails as you describe.

I want to investigate why this WOZ is so big (eg. perhaps track data is output for every quarter track? ...which fits with the size, eg. 228K x4 = 912K, where 228K is the size of the "DOS 3.3 System Master.woz")

Tagging as a bug, since this should still work.

---

Developer notes:
- `CImageHelperBase::CheckNormalFile()` does a size check against `GetMaxImageSize()`, which is just over 800KiB.
- In the `Detect()` loop, `CHDVImage::Detect()` returns a match (as the size is >=800KiB).

If I skip both of these, then the .woz boots and works fine.

NB. I've no idea yet why the WOZ is so big.

**Comment by tomcw** [comment] 2023-06-18 15:05
btw, @Udderdude I found `a2woz` here: https://github.com/adafruit/a2woz
Is this what you are used to create this WOZ?

**Comment by Udderdude** [comment] 2023-06-18 16:58
Yes, that's it.

**Comment by tomcw** [comment] 2023-06-29 20:56
>I want to investigate why this WOZ is so big (eg. perhaps track data is output for every quarter track? ...which fits with the size, eg. 228K x4 = 912K, where 228K is the size of the "DOS 3.3 System Master.woz")

Yes, there's track data for every quarter track. See this `wozardry` dump:

[Apple II System Disk.txt](https://github.com/AppleWin/AppleWin/files/11910449/Apple.II.System.Disk.txt)

**Comment by tomcw** [comment] 2023-06-29 21:02
Fixed in faff74a, and tested with .woz, .woz.gz & .woz.zip.

I still include a check for a the .woz filesize - this time pathologically large: ~7MB (based on a FLUX track for every quarter track!).

**Closed by tomcw** 2023-06-29 21:02 UTC
Labels: bug

**Comment by tomcw** [comment] 2023-07-29 12:54
@Udderdude - Fixed in [AppleWin 1.30.15.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.15.0).
