### ISSUE TITLE
Drive sounds

### ISSUE THREAD

**Issue by Harcolas** [AppleWin/AppleWin#760] opened 2020-02-17 23:13 UTC
Hello team,

This is my first post...huge fan of emulation since...zx81 emulation on a Zx Spectrum...

Just a request : could it be possible to get the sounds of the drives during R/W operations ? Something like Winuae offers.

I guess that can be something to increase the feeling we are using a real Apple//.

So many thanks for what you are doing.

Arnaud.

**Comment by Michaelangel007** [comment] 2020-02-18 20:25
Virtual ][ has this and is awesome for nostalgia -- especially running Beagle Bros `CHUGGACHUGGA` 2 liner!

This is a duplicate of #9 -- yes, a feature request that goes back a long ways!

**Closed by Michaelangel007** 2020-02-18 20:25 UTC
