### ISSUE TITLE
Feature request: Unlocked mounting of disk images

### ISSUE THREAD

**Issue by Sunspark-007** [AppleWin/AppleWin#1300] opened 2024-05-01 00:41 UTC
I read a comment that said in a really old AppleWin version 1.17.2 it was still possible to leave a disk image mounted and still have it be written to with cadius and the like without having to exit the emulator or unmount it & reboot.

I understand why that was fixed, but from a development standpoint, it seems like it would really speed things up if you could just leave the image mounted and emulator running knowing that you wouldn't be updating the file to a running program.

Is it possible that this behaviour could be returned with an advanced usage checkbox?

**Comment by tomcw** [comment] 2024-05-01 20:23
There was some discussion of improving the workflow for HD images in #1219.
I'm going to close this as a duplicate of that.

**Closed by tomcw** 2024-05-01 20:23 UTC
