### ISSUE TITLE
French Rom toggle on 65C02 apple //e and apple //c

### ISSUE THREAD

**Issue by aram-gilbert** [AppleWin/AppleWin#574] opened 2018-08-07 15:39 UTC
![winapple - french characters set missing](https://user-images.githubusercontent.com/42181907/43786189-5da35b02-9a68-11e8-89d9-d356290b6cb5.jpg)

Dears, 
I'll be pleased to get a new toggle as I have on my Apple //e 65c02 - French. 
There is a small switch under the keyboard to select which character set to use, depending on the software used. 
I've attached a screenshot of AppleWorks French starting using the current WinApple rom. 
Thanks for your great software ! It let me use all my software and data ! 

  Kind regards,

  Alexandre GILBERT

**Comment by tomcw** [comment] 2018-08-08 21:16
Have you got a ROM image of the French keyboard character ROM?

**Comment by sicklittlemonkey** [comment] 2018-08-09 02:13
Hi Tom.

Do you mean the video ROM? I'm not sure if the keyboard layout was
different, but all characters (in fact, every possible video output bit
sequence) are stored in the Video ROM, including the text character bitmaps.

Probably the biggest collection that I know of is here:
https://downloads.reactivemicro.com/Apple%20II%20Items/ROM_and_JEDEC/IIe/Video%20ROM/

Cheers,
Nick.

**Comment by MarcoVerpelli** [comment] 2018-08-09 08:31
Also the Italian version of the Apple // c has the ability to show the nationalized characters.

In the (now deceased) site http://www.ctrl-pomme-reset.fr there was instructions on how to replace the font image with one of user choice using  a resource editor

Marco

**Comment by tomcw** [comment] 2018-08-09 17:16
Thanks Nick - from your URL, under Dual-Euro, are the 8K video ROMs (French, German, UK).
No Italian though. @MarcoVerpelli - do you have a dump of your ROM?

**Comment by tomcw** [comment] 2018-08-09 17:31
NB. This dsk image gives a similar display to the original comment above:

ftp://ftp.apple.asimov.net/pub/apple_II/images/non-english/french/apple/AppleWorks%20v1.2%20-%20boot%20(French).DSK

**Comment by MarcoVerpelli** [comment] 2018-08-09 17:35
No sorry. Never opened it in my life, and even if I opened it I would have no idea how to do a ROM dump. Time ago some one told me that the hardware has to do with electricity, but I think he wanted to make fun of me, nobody knows what the electricity really is!

**Comment by sicklittlemonkey** [comment] 2018-08-09 22:17
Hmm, from this list:
ftp://ftp.apple.asimov.net/pub/apple_II/documentation/hardware/misc/Apple%20II%20Common%20ROM%20Numbers.txt

... we're looking for ROM 342-0276-A //c, //e (enhanced) Char Gen Italian

This wonderful Italian retro museum:
https://museo.freaknet.org/it/restauro-apple-c-in-corso/
... possibly has it here!
https://museo.freaknet.org/files/apple-2c/
a2-chargen-342-0276-A-2764.bin

I haven't checked the contents yet.

Cheers,
Nick.

**Comment by tomcw** [comment] 2018-08-10 11:43
Great hunting, Nick!
I have a bit of C code to dump the 8K video ROMs to ascii-pixel representation. I will check it this weekend.

**Comment by tomcw** [comment] 2018-08-12 20:25
Yes, both the French and Italian are video char ROMs.
Here's a bit of code to dump them:

```
#include <stdio.h>

int main(int argc, char* argv[])
{
	const int CHAR_ROM_SIZE = 8192;
	unsigned char nBuffer[CHAR_ROM_SIZE];
	FILE* hFile;
	char* fileName;
	if (argc == 1) fileName = "UKCHAR.ROM";
	else fileName = argv[1];
	hFile = fopen(fileName, "rb");
	if (hFile == NULL)
	{
		printf("Failed to open %s\n", fileName);
		return 1;
	}

	unsigned int nLen = fread(nBuffer, 1, CHAR_ROM_SIZE, hFile);
	fclose(hFile);
	if (!nLen)
	{
		printf("Failed to read bytes\n");
		return 1;
	}

	const int NUM_CHARS = nLen / 8;
	for (int i=0; i<NUM_CHARS; i++)
	{
		for (int j=0; j<8; j++)
		{
			unsigned char n = nBuffer[i*8+j];
			for (int k=0; k<8; k++)
			{
				// Output LSB on left & MSB on right (ie. backwards)
				printf("%c", n&(1<<k) ? '#' : '.');
			}
			printf("\n");
		}
		printf("\n");
	}
	return 0;
}
```

**Comment by aram-gilbert** [comment] 2018-08-15 13:56
Tom, 
  Maybe my C knowledge is a bit old, but my opinion on your code : 
1. In C on apple //e ; I only know Aztec C that could do that and to compile, it takes 20 minutes and 4 floppy change. 
2. I don't see the base address of the ROM in the C source. May you tell me what is the base address in hex ?
3. I suggest making an applesoft basic program to "peek" the ROM values and display it in hex table. Then, using a picture of the screen then OCR it to get the data. A bit tricky but restarting the serial port on my old Apple //e, full of dust won't be easy. 

Thanks for you interest in my post ! 

  Kind regards,

  Alexandre.

**Comment by tomcw** [comment] 2018-08-15 17:15
Hi Alexandre,
>Maybe my C knowledge is a bit old, but my opinion on your code :

Actually my code was for a Window (or Linux) machine... not an Apple II!
So from a Windows machine, build the code (eg. using Visual Studio), then you can dump the 4K or 8K video ROM file to an ascii output.

**Comment by sicklittlemonkey** [comment] 2018-08-15 21:40
On Thu, 16 Aug 2018 at 01:56, aram-gilbert <notifications@github.com> wrote:
> I suggest making an applesoft basic program to "peek" the ROM values and
display it in hex table. Then, using a picture of the screen then OCR it to
get the data. A bit tricky but restarting the serial port on my old Apple
//e, full of dust won't be easy.

Hi Alexandre.

The video ROM is not addressable from within the Apple II.

In any case, we now have the ROMs, and IMO it would be great to be able to
select different character ROMs.
But someone needs to have the time to write the feature ...

Cheers,
Nick.

**Comment by tomcw** [comment] 2018-08-16 09:35
Hi Nick,
I'm just thinking a little about the spec for supporting video (character) ROMs.

In AppleWin, there are many models of Apple II supported (ie. II, II+,//e, Enhanced //e and clones too), and you wouldn't want (eg) an enhanced //e ROM used when emulating a II or II+. But maybe you have a custom French Apple II+ video ROM, which you only want used with a II+ machine. So potentially there's a complex combination of Apple II models x video ROMs that could be supported!

IMO the mainline use-case is supporting different video ROMs for the Enhanced //e.

So we could support this via:
1. a cmd-line switch to specify an alternative video ROM _just for_ the Enhanced //e
   - I'd want to avoid specifying an Apple II type on the cmd line too, as I feel this over complicates things
2. a GUI Configuration drop-down to specify a video ROM language, and if there is an (AppleWin) build-in video ROM for that language then it would take affect
   - this can work for models other than Enhanced //e, assuming those video ROMs exist and have been built into AppleWin
   - eg. this would allow for French unenhanced and enhanced video ROMs to work with unenhanced and enhanced machines respectively

**Comment by tomcw** [comment] 2018-11-11 15:38
OK, I've found 3 French character/video ROMs, all **different**(!):

1. Apple IIe Video - Custom - French-US - Enhanced - 2764.bin
    - 8KiB, ReactiveMicro.com [here](https://downloads.reactivemicro.com/Apple%20II%20Items/ROM_and_JEDEC/IIe/Video%20ROM/Dual-Euro/Apple%20IIe%20Video%20-%20Custom%20-%20French-US%20-%20Enhanced%20-%202764.bin).
    - Contains 32 chars of mousetext at char offset 576
2. Apple IIe Video French-US - Unenhanced - 342-0274-A - 2764.bin
    - 8KiB, ReactiveMicro.com [here](https://downloads.reactivemicro.com/Apple%20II%20Items/ROM_and_JEDEC/IIe/Video%20ROM/Dual-Euro/Apple%20IIe%20Video%20French-US%20-%20Unenhanced%20-%20342-0274-A%20-%202764.bin).
    - No mousetext (eg. at char offset 576 just 32 non-inverse chars: @,A,B,C,...[,\\,],^,_)
    - But from the asimov list of common ROM numbers (ftp://ftp.apple.asimov.net/pub/apple_II/documentation/hardware/misc/Apple%20II%20Common%20ROM%20Numbers.txt), this ROM should be enhanced:
    - `342-0274-A      //c, //e (enhanced) Char Gen French`
3. VID-342-274A.bin
    - 16KiB (first 8KiB is all 0xFF's), asimov here: ftp://ftp.apple.asimov.net/pub/apple_II/emulators/rom_images/VID-342-274A.bin
    - Contains 32 chars of mousetext at char offset 64
    - Contains 32 chars of mousetext at char offset 576

**Comment by aram-gilbert** [comment] 2018-11-11 16:42
It sounds good ? How can I help ? Testing ?

De : TomCh <notifications@github.com>
Envoyé : dimanche 11 novembre 2018 16:38
À : AppleWin/AppleWin <AppleWin@noreply.github.com>
Cc : Alexandre GILBERT <alexandre@gilbert-consultant.com>; Author <author@noreply.github.com>
Objet : Re: [AppleWin/AppleWin] French Rom toggle on 65C02 apple //e and apple //c (#574)


OK, I've found 3 French character/video ROMs, all different(!):

  1.  Apple IIe Video - Custom - French-US - Enhanced - 2764.bin
     *   8KiB, ReactiveMicro.com here<https://downloads.reactivemicro.com/Apple%20II%20Items/ROM_and_JEDEC/IIe/Video%20ROM/Dual-Euro/Apple%20IIe%20Video%20-%20Custom%20-%20French-US%20-%20Enhanced%20-%202764.bin>.
     *   Contains 32 chars of mousetext at char offset 576
  2.  Apple IIe Video French-US - Unenhanced - 342-0274-A - 2764.bin
     *   8KiB, ReactiveMicro.com here<https://downloads.reactivemicro.com/Apple%20II%20Items/ROM_and_JEDEC/IIe/Video%20ROM/Dual-Euro/Apple%20IIe%20Video%20French-US%20-%20Unenhanced%20-%20342-0274-A%20-%202764.bin>.
     *   No mousetext (eg. at char offset 576 just 32 non-inverse chars: @,A,B,C,...[,\,],^,_)
     *   But from the asimov list of common ROM numbers (ftp://ftp.apple.asimov.net/pub/apple_II/documentation/hardware/misc/Apple%20II%20Common%20ROM%20Numbers.txt), this ROM should be enhanced:
     *   342-0274-A //c, //e (enhanced) Char Gen French
  3.  VID-342-274A.bin
     *   16KiB (first 8KiB is all 0xFF's), asimov here: ftp://ftp.apple.asimov.net/pub/apple_II/emulators/rom_images/VID-342-274A.bin
     *   Contains 32 chars of mousetext at char offset 64
     *   Contains 32 chars of mousetext at char offset 576

**Comment by tomcw** [comment] 2018-11-11 21:12
I'm just making some preliminary notes - but as soon as I have something working, I'll let you have a build to test.

**Comment by tomcw** [comment] 2018-11-14 21:33
@aram-gilbert,

Here's a experimental build (zipped) with support for other video ROMs: [Applewin-1.27.11.0.zip](https://github.com/AppleWin/AppleWin/files/2582700/Applewin-1.27.11.0.zip)

Just extract it over the top of AppleWin 1.27.10.0.

To use it, from the command line (cmd shell):
`>applewin.exe -videorom <filename>`

EG.
`>Applewin.exe -videorom "Apple IIe Video - Custom - French-US - Enhanced - 2764.bin"`

It supports video ROM bin files of size 8KiB or 16KiB (the latter it just uses the top 8KiB). 4KiB files are not implemented yet.

I've tested it on "AppleWorks v1.2 - boot (French).dsk" with the 3 ROM files listed in a previous comment.

NB. There's no GUI configuration support (it's command line only).

Please give it a test and let me know how you get on.

**Comment by tomcw** [comment] 2018-11-14 21:43
I forgot to mention that this new video rom **only works** in Enhanced //e mode.

**Comment by tomcw** [comment] 2018-11-14 21:46
And a bonus (and as @MarcoVerpelli mentions above) you can now enjoy French Touch's [Block Ansi Anthology](http://ctrl.pomme.reset.free.fr/index.php/tag/french-touch/page/2/) with this command line:

`>Applewin.exe -videorom eprom2164.bin`

**Comment by tomcw** [comment] 2018-11-16 08:31
Actually (having read Sather on video ROMs), my implementation isn't quite right: it'll show US (alt char set=0) & Euro (alt char set=1). What I need to do it support the rocker switch under the keyboard (for PAL //e's) to provide this:
- US chars; alt char set=0|1 (rocker switch=0)
- Euro chars; alt char set=0|1 (rocker switch=1)

**Comment by aram-gilbert** [comment] 2018-11-16 12:34
Thanks Tom for your time and effort. Maybe to make it easier, why not considering the rocker switch to 1 when video rom is passed in command line. At least for testing while you are developping the rocker switch emulation. It may not be piece of cake. Thanks for taking care of that request.

**Comment by tomcw** [comment] 2018-11-17 17:38
@aram-gilbert, OK here's a release build, [AppleWin 1.27.12.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.27.12.0).

Use F10 to toggle the rocker switch (with it defaulting to the European video ROM, as you suggested).
See the release notes [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.27.12.0) for a bit more info.

I also tested with the 4K Canadian video ROM, [here](https://downloads.reactivemicro.com/Apple%20II%20Items/ROM_and_JEDEC/IIe/Video%20ROM/Apple%20IIe%20Video%20French%20Canadian%20-%20Enhanced%20-%202732.bin).
NB. F10 has no effect for 4K video ROMs.

Does this new build work for you?

**Comment by aram-gilbert** [comment] 2018-11-17 18:31
@tomcw : Works fine ! I guess I should find the proper ROM now. The "apple-?" for assistance is converted to an A-?. When I press F10, I got the EmptyApple-?
It's not in the program, but in the rom file. 

Thank you so much for making it live !


![apple iie test](https://user-images.githubusercontent.com/42181907/48664458-fcb12400-ea9e-11e8-86e7-0abc037c5db9.JPG)

**Comment by MarcoVerpelli** [comment] 2018-11-17 18:45
I can confirm that this ROM works very well with the Italian language, it seems to be my real iron // c

https://museo.freaknet.org/files/apple-2c/a2-chargen-342-0276-A-2764.bin

Marco

**Comment by tomcw** [comment] 2018-11-17 21:58
Thanks both for confirming.

@aram-gilbert: re. A-?
It's possible that the video ROM that you chose doesn't have the mouse-text characters.
Which French video ROM are you using?

**Comment by MarcoVerpelli** [comment] 2018-11-18 10:00
We can always use this to make our custom ROMs

https://github.com/robmcmullen/omnivore

**Comment by aram-gilbert** [comment] 2018-11-18 14:16
I used both video ROM I could get. To be honest, I don’t remember if it was the A-? on the real one. I should restart my old apple… Maybe it was a turn around used in time ;o)

De : TomCh <notifications@github.com>
Envoyé : samedi 17 novembre 2018 22:59
À : AppleWin/AppleWin <AppleWin@noreply.github.com>
Cc : Alexandre GILBERT <alexandre@gilbert-consultant.com>; Mention <mention@noreply.github.com>
Objet : Re: [AppleWin/AppleWin] French Rom toggle on 65C02 apple //e and apple //c (#574)


Thanks both for confirming.

@aram-gilbert<https://github.com/aram-gilbert>: re. A-?
It's possible that the video ROM that you chose doesn't have the mouse-text characters.
Which French video ROM are you using?

**Comment by tomcw** [comment] 2018-12-08 13:13
Added tests here: https://github.com/AppleWin/AppleWin-Test/commit/2e9799335000119eb5703ca26af21942fbb8dfca.

**Comment by tomcw** [comment] 2018-12-08 13:57
Closing this issue, as it's been confirmed working.

**Closed by tomcw** 2018-12-08 13:57 UTC
Labels: enhancement
