### ISSUE TITLE
SSC ACIA Status Register bit7 not set when IRQ enabled and using TCP Port 1977

### ISSUE THREAD

**Issue by burniouf** [AppleWin/AppleWin#308] opened 2015-12-13 12:29 UTC
Applewin 1.25.0.4
Serial Port set as "TCP"

When Enabling IRQ in ACIA CMD register (with value %00000101) an IRQ signal is generated (properly caught by IRQ handler) but bit 7 of ACIA status Register is not set to "1".

Seems OK when Serial Port set as "COM1"

**Comment by tomcw** [comment] 2015-12-27 17:04
I took a quick look.

Comparing to `CommReceive()`, it looks like `CommTcpSerialReceive()` needs to also set `m_vbRxIrqPending`. This flag is then checked (and cleared) in `CommStatus()`.

**Comment by burniouf** [comment] 2015-12-27 20:18
personaly, i would add : 
"m_vbRxIrqPending = true;" 
after line 395 in AppleWin / source / SerialComms.cpp 
am i right?

when release 1.26 (with this fix) will be released?

**Comment by sicklittlemonkey** [comment] 2015-12-28 08:24
Looks like Tom added some emulation tweaks after I hacked in the TCP serial
code. Now the TCP code needs the same tweaks.

It would be less of a problem if we had been able to use proper
object-oriented principles, but the AppleWin code doesn't usually lend
itself to that - and no doubt I was busy/lazy.

Cheers,
Nick.

**Comment by tomcw** [comment] 2015-12-28 11:28
> It would be less of a problem if we had been able to use proper object-oriented principles

Agreed! :)

> when release 1.26 (with this fix) will be released?

I want to complete #260, and have a small window to do this now... so January.

**Comment by burniouf** [comment] 2016-01-04 10:21
Something else in the same area that should be more an enhancement than a bug fix, but,
is it possible to set DSR and CTS lines low when TCP connection is established, and high when TCP connection is dropped?

**Comment by sicklittlemonkey** [comment] 2016-01-04 20:36
I created a separate issue for that enhancement:
https://github.com/AppleWin/AppleWin/issues/311

Cheers,
Nick.

**Comment by tomcw** [comment] 2017-12-19 21:54
The fix was trivially simple (for the ACIA Status.Interrupt not being set) ...but I've not tested it!

>is it possible to set DSR and CTS lines low when TCP connection is established, and high when TCP connection is dropped?
DSR: see #386, and can be tested with AppleWin 1.26.3.0 onwards.
CTS/RTS (Clear To Send/Ready To Send): Maybe instead this is DCD/DTR - see #386 (and again AppleWin 1.26.3.0).

**Comment by burniouf** [comment] 2017-12-19 22:06
Yeah!!!
2 years later, i must dig in the code of A2osX to find where i met this issue.
Which version should i use to check this bugfix ?

**Comment by tomcw** [comment] 2017-12-19 22:52
Great! I didn't know if you were still about to test this.
I'll do a build tomorrow and put the link here.

**Comment by tomcw** [comment] 2017-12-20 21:10
Here's the new build of [AppleWin 1.26.3.6](https://github.com/AppleWin/AppleWin/releases/download/v1.26.3.6/AppleWin1.26.3.6.zip) (tagged as pre-release).

**Comment by burniouf** [comment] 2017-12-20 22:14
Bit 7 of ACIA Status seems to be set properly, now.
I uncommented the fix for this bug line 252 in :

https://github.com/burniouf/A2osX/blob/master/DRV/SSC.DRV.S.txt

but the driver is not accepting incoming char any more....
must resume where i left 2 years ago...
Actually, usng a simplier IRQ manager:

*--------------------------------------
* IRQ Handler
* on exit, CC if handled
*--------------------------------------
IRQ				ldx DEVSLOTn0
				lda SSC.STATUS,x
				
*				and #SSC.STATUS.IRQ		Useless
				bpl .9					IRQ from this device ? no, exit !!!!Applewin bug #308!!!!

				bit #SSC.STATUS.RDRF	incoming char?
				beq .4					

*------------ IRQ In

				pha						save SSC.STATUS
				
				lda INBUF.HEAD
				tay						save actual head for later
				
				inc
				and #BUF.MASK
				cmp INBUF.TAIL				
				beq .3					buffer full, discard and exit
				
				sta INBUF.HEAD
				
				lda SSC.DATA,x			read data to clear IRQ
				sta INBUF,y

.3				pla						get back SSC.STATUS
				
*------------ IRQ Out
				
.4				bit #SSC.STATUS.TDRE
				beq .8					no transmition possible....

				ldy OUTBUF.TAIL			something to transmit ?
				cpy OUTBUF.HEAD
				beq .8					in that case, HOW TO CLEAR IRQ ????
				
				lda OUTBUF,y
				sta SSC.DATA,x			write data to clear IRQ
				
				tya
				inc
				and #BUF.MASK
				
				sta OUTBUF.TAIL	
				
.8				clc
				rts
				
.9				sec
				rts

.....not much success...digging into 6551 datasheet...
i ll keep you informed.

**Comment by tomcw** [comment] 2017-12-20 22:33
Hi Rémy - out of interest, what are you using for development? AppleWin, other emulator or real h/w?

**Comment by burniouf** [comment] 2017-12-21 07:07
i use mainly AppleWin....
and JACE because it supports DHGR mixed mode & ThunderClock emulation...
...and of course testing on readl H/W. 
see:
https://github.com/burniouf/A2osX/issues/29

I could be a very cool AppleWin implements DHGR Mixed Mode!

**Comment by tomcw** [comment] 2017-12-21 11:44
>I could be a very cool AppleWin implements DHGR Mixed Mode!

AppleWin 1.26 versions should support all graphics modes (if not then this is a bug).

By DHGR mix mode do you mean this:
- top 160 lines DHGR
- bottom 32 lines either TEXT40 or TEXT80
?

**Comment by burniouf** [comment] 2017-12-21 12:00
no,

if bit 7=1 -> color
if bit 7= 0 -> mono

See Chapter 6 in:

ftp://ftp.apple.asimov.net/pub/apple_II/documentation/hardware/video/Ext80ColumnAppleColorCard.pdf

And:

https://patentimages.storage.googleapis.com/pdfs/US4631692.pdf

already implemented in JACE.

**Comment by burniouf** [comment] 2017-12-21 12:03
Finally made A2osX SSC.I.drv working in AppleWin....

strange behaviour...when reading INPUT register after IRQ, seems internal queue not advancing to next char...added a loop in IRQ handler to bypass.

must run this new driver on REAL hardware.

**Comment by burniouf** [comment] 2017-12-21 12:04
*--------------------------------------
* IRQ Handler
* on exit, CC if handled
*--------------------------------------
IRQ				ldx DEVSLOTn0
				lda SSC.STATUS,x
				
*				and #SSC.STATUS.IRQ		Useless
				bpl .9					IRQ from this device ? no, exit !!!!Applewin bug #308!!!!

				bit #SSC.STATUS.RDRF	incoming char?
				beq .3					

*------------ IRQ In

.1				lda INBUF.HEAD
				tay						save actual head for later
				
				inc
				and #BUF.MASK
				cmp INBUF.TAIL				
				beq .2					buffer full, discard and exit
				
				sta INBUF.HEAD

				lda SSC.DATA,x			read data to clear IRQ
				sta INBUF,y

.2				lda SSC.STATUS,x
				bit #SSC.STATUS.RDRF	incoming char?
				bne .1
				
*------------ IRQ Out
				
.3				bit #SSC.STATUS.TDRE
				beq .8					no transmition possible....

.4				ldy OUTBUF.TAIL			something to transmit ?
				cpy OUTBUF.HEAD
				beq .8					in that case, HOW TO CLEAR IRQ ????
				
				lda OUTBUF,y
				sta SSC.DATA,x			write data to clear IRQ
				
				tya
				inc
				and #BUF.MASK
				
				sta OUTBUF.TAIL	
				
				lda SSC.STATUS,x
				bit #SSC.STATUS.TDRE
				bne .4
				
.8				clc
				rts
				
.9				sec
				rts
*--------------------------------------

**Comment by tomcw** [comment] 2017-12-21 13:08
>strange behaviour...when reading INPUT register after IRQ, seems internal queue not advancing to next char...added a loop in IRQ handler to bypass.

By internal queue - do you mean your 6502 code? Or AppleWin's internal queue?
Which code is the loop you added?

btw:
- reading SSC.STATUS will de-assert the IRQ (not SSC.DATA)
- AppleWin doesn't yet support the SSC's "TX register empty" interrupt (just in case you try to test with AppleWin and wonder why it's not working!)

**Comment by tomcw** [comment] 2017-12-21 19:00
>>By internal queue - do you mean your 6502 code? Or AppleWin's internal queue?
>sorry, i meant APPLEWIN queue (if exists)

Your code:

```
*------------ IRQ In

.1			lda INBUF.HEAD
			tay			save actual head for later
				
			inc
			and #BUF.MASK
			cmp INBUF.TAIL				
			beq .2			buffer full, discard and exit
				
			sta INBUF.HEAD

			lda SSC.DATA,x		read data to clear IRQ
			sta INBUF,y

.2			lda SSC.STATUS,x
			bit #SSC.STATUS.RDRF	incoming char?
			bne .1
```

My understanding is that your code will just keep reading SSC.DATA,x until SSC.STATUS.RDRF becomes 0.

AppleWin has an internal buffer of 128 bytes, and it will receive up to 128 for each TCP socket recv(). So (depending on what data you are sending to AppleWin) it's very likely that packets of >1 byte will be received, and so your code will loop until it's read all the data from that TCP recv() buffer.

I assume that you are not missing any data?
And also that you are not getting any duplicate or bad data?

**Comment by burniouf** [comment] 2017-12-21 19:36
yes, this way it works very well in AppleWin, no miss, no duplicate.....but i don't know the behaviour on real hardware after this change....
for now i'm focused on DHGR & GUI development, and i'm lacking beta testers.. :-(

any chance TX register empty  IRQ implemented ?

**Comment by tomcw** [comment] 2017-12-22 12:12
>any chance TX register empty IRQ implemented ?

Yes, should be doable. I've created #522 to track this.

**Comment by tomcw** [comment] 2017-12-22 12:36
And I've created #523 to track DHGR Mixed Mode.

**Comment by tomcw** [comment] 2017-12-30 22:40
@burniouf - btw your code is doing this (in 2 places):
```
 sta SSC.DATA,x 
```

...which is doing a **false read** of SSC.DATA+X too!

On a real Apple II you could lose input data (receive data) because of this false read.
NB. AppleWin doesn't do this false read - a good example of why you should always test on real hardware.

See how the SSC's firmware avoids this false read by doing this (at $CC0D):
```
 sta $BFFF,Y
```

**Comment by burniouf** [comment] 2018-01-01 12:15
Except that a2osx is targeting 65c02 or higher , which is NOT doing false read
I experienced this while writing uthernet II driver

**Comment by tomcw** [comment] 2018-01-01 17:39
From Sather's "Understanding the Apple IIe", table 4.3 "65C02 Instructions", row 22 shows that just like for the 6502, the STA ABS,X (no PX) still does a false read at address ABS+X. Also on the preceding page (4-26), he explains that the disk II's logic sequence is designed around  the "STA $C080,X" instruction doing this double access.

**Comment by tomcw** [comment] 2018-04-08 21:29
@burniouf above you reported:
>strange behaviour...when reading INPUT register after IRQ, seems internal queue not advancing to next char

This just got fixed in a78f1e04da0f5b87116af6e3c4d8dd73f282129a:
- _Fixed TCP mode which was only generating an IRQ for first byte received_

I'll update this issue when there's a new build.

**Comment by burniouf** [comment] 2018-04-09 19:27
Great!

Let me know when build s ready, in the meantime, i 'll rewrite from scratch these SSC drivers to remove this "false read" code...

Thanx

**Comment by tomcw** [comment] 2018-04-12 21:12
New AppleWin 1.27.2.0 build [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.27.2.0).
Let me know how you get on.

**Comment by tomcw** [comment] 2018-04-13 20:59
btw, see this project for my SSC tests for {Polling|Interrupt x Rx|Tx}:
https://github.com/AppleWin/AppleWin-Test/tree/master/Projects/GH522-SSC-TX-RX

**Comment by burniouf** [comment] 2018-04-14 06:02
At my side, seems to work better, now.
Implemented in this driver:

https://github.com/burniouf/A2osX/blob/master/DRV/X.SSC.DRV.S.txt

(note : rewrote the whole stuff to avoid "false read)

I will test this on real hardware, an then add DSR/CTS monitoring.

Do i need special switch in Applewin cmd line to enable the TCP/IP  DSR/CTS functionality ?

**Comment by tomcw** [comment] 2018-04-14 09:55
>Do i need special switch in Applewin cmd line to enable the TCP/IP DSR/CTS functionality ?

For CTS (and RTS), these just work.
For DSR (and DCD, DTR), you'll need to specify the -modem switch (or -dtr/-dcd/-dsr for the specific signal you want AppleWin to support).

**Comment by burniouf** [comment] 2018-04-14 12:42
i added the -modem switch to the cmd line, and tried monitoring the DTR line with not much success. :-(
i use putty to connect to A2osX 127.0.0.1:1977. i connect succesfully to A2osX/SSC.I.DRV (RX/TX IRQ working properly now, no lost chars...etc...) but when i close PUTTY to drop the TCP connection....the DTR bit in STATUS register does not go high...

**Comment by tomcw** [comment] 2018-04-14 17:01
>but when i close PUTTY to drop the TCP connection....the DTR bit in STATUS register does not go high...

Actually the Status reg contains DSR and DCD (it's the Control reg that has DTR). But I assume this is a typo and you mean DSR (not DTR).

Anyway, I see what's wrong...
The Status register's DSR and DCD bits are only supported when using a real COM port. For TCP they always remain zero.

And it's the same for CTS (read from the DIPSW2 reg), ie. it's only supported for a real COM port, not TCP (always zero).

I'll re-open this issue, and see what DSR+DCD emulation I can provide when using TCP mode.

**Comment by burniouf** [comment] 2018-04-14 18:39
oops, yes ! i meant DSR.

btw, the current Applewin status allow me to go ahead with many pending features in A2osX....
Thanx for your support.

**Comment by tomcw** [comment] 2018-04-14 20:38
This build should support DSR, DCD (and CTS) for the TCP mode.
(I'm testing with PUTTY too)
[AppleWin1.27.3.0.zip](https://github.com/AppleWin/AppleWin/files/1911033/AppleWin1.27.3.0.zip)

**Comment by burniouf** [comment] 2018-04-14 20:49
IT WORKS!!!

**Comment by burniouf** [comment] 2018-04-14 20:50
![image](https://user-images.githubusercontent.com/8941204/38772406-3a0dd4a6-4036-11e8-8f5f-c30545fa8193.png)

**Comment by burniouf** [comment] 2018-04-14 20:51
![image](https://user-images.githubusercontent.com/8941204/38772417-57c4e4bc-4036-11e8-939c-ac5e4b48fcd5.png)

**Comment by burniouf** [comment] 2018-04-14 20:52
now LOGIN & SHELL are properly killed when a cut the link!

**Comment by burniouf** [comment] 2018-04-14 20:52
![image](https://user-images.githubusercontent.com/8941204/38772427-90017c64-4036-11e8-9ae2-476bcaaabee4.png)

**Comment by burniouf** [comment] 2018-04-14 20:53
...and next connection is prompted at LOGIN again.

many thanx.
Remy

**Comment by tomcw** [comment] 2018-05-26 16:18
NB. Official release [AppleWin1.27.4](https://github.com/AppleWin/AppleWin/releases/download/v1.27.4.0/AppleWin1.27.4.0.zip) (superseding 1.27.3).

**Closed by tomcw** 2018-05-26 16:18 UTC
Labels: bug

**Comment by burniouf** [comment] 2018-05-26 18:31
Just to be sure...i need to test again WITHOUT -modem switch, right ?

**Comment by tomcw** [comment] 2018-05-27 08:31
Yes, correct: without the -modem switch.

Details the -modem switch (alias: -dcd) can be used in COM mode to use the actual value of DCD - the default (ie. without this switch) is for DCD to mirror the state of DSR.

NB. In TCP mode, this switch has no affect. Whilst there's a TCP connection then DCD and DSR will both be low (ie. active). The same for CTS.

**Comment by burniouf** [comment] 2018-05-28 17:21
AppleWin 1.27.4 Without "-modem"
I confirm the bahaviour is as expected.
same test as above succedeed.
Good Job!

**Comment by tomcw** [comment] 2018-05-29 20:41
Thanks for re-checking this - it's good to know nothing has broken (but I do have regression tests now for this behaviour).
