### ISSUE TITLE
Can't compile in Visual Studio 2015

### ISSUE THREAD

**Issue by robinhood2014** [AppleWin/AppleWin#329] opened 2016-07-01 16:56 UTC
I can't compile the AppleWin solution in Visual Studio 2015. The solution file which is named as being compatible with VS2015 is actually only compatible with VS2013, and I can't upgrade the build tools by right-clicking the solution in Project Explorer and choosing Retarget Solution -- after providing a dialog box where my only option is a drop-down list box containing only one option (8.1), nothing seems to happen when I click OK, although the Output pane says that five projects were successfully retargeted. What's the issue here?

**Comment by tomcw** [comment] 2016-07-01 17:25
The problem is that AppleWinExpress2015.vcxproj references the 2013 project files - a simple mistake made when migrating the VS2013 to VS2015. I'll check in a fix...

**Comment by tomcw** [comment] 2016-07-01 21:13
@robinhood2014 - can you try that?

**Comment by robinhood2014** [comment] 2016-07-04 21:30
Thanks Tom, that seems to have done it. Now, where is the code in which, when you Control-click the "full screen" button, it will switch from a small window to a big window? I want to see if I can add similar functionality to another Apple II emulator, namely GSport.

**Comment by sicklittlemonkey** [comment] 2016-07-04 22:56
Heh. I don't think the AppleWin code will really help you.

This commit is where I fixed the Windows fullscreen behaviour of GSPort.
These are the same parts you'll need to change if you want to implement a
larger window.
https://sourceforge.net/p/gsport/code/355/
i.e.
win_console.c
win_generic.c

You may want to wait until after KFest since it looks like Dagen Brock has
been working on an SDL fork of GSPort.
Whether it will get merged back hasn't been revealed yet.

Cheers,
Nick.

**Closed** 2016-07-26 17:49 UTC
