### ISSUE TITLE
Ask to amend  the apple ii e emulator in window to 42 tracks version.Or build a new apple II e emulator in window for 42 tracks.

### ISSUE THREAD

**Issue by ngchungtak** [AppleWin/AppleWin#1281] opened 2024-02-20 07:57 UTC
I have 42 tracks data disk, in apple ii e emulator in window that is 40 tracks version limit. I wish to have a apple ii e emulator in window that is 42 tracks version. I know that there will be a change in file src/emulator/devices/convertds2woz.ts file. But there is in network. I wish to have a version in 42 tracks apple ii e emulator in window. 
Please programmer  amend  the apple ii e emulator in window to 42 tracks version.Or build a new apple II e emulator in window for 42 tracks.

**Comment by ngchungtak** [comment] 2024-02-20 12:42
Is it possible to change the apple ii e emulator in window software into a whole package form so that there will be possible for us to amend the version in our computer without depending the network software to observe ? I mean that  the apple ii e emulator in window is in whole package form so that we can alter the parameter in our own computer to obtain the new state.e.g. 42 tracks version.

**Comment by ngchungtak** [comment] 2024-02-21 07:40
Is it possible add a parameter in changing maximium tracks allowed to read in config option in apple II e emulator in window.eg. change 40 tracks to 42 tracks.

**Comment by tomcw** [comment] 2024-02-22 08:05
What is your use-case for wanting 42 tracks?
Ah, over in #568 you mention cracking a game so it fits on a single side.

Anyway, this issue is a duplicate of #568, so I will close this one.

**Closed by tomcw** 2024-02-22 08:05 UTC
Labels: duplicate
