### ISSUE TITLE
Support Extended 80 Column / AppleColor DHR Modes (feature request)

### ISSUE THREAD

**Issue by inexorabletash** [AppleWin/AppleWin#575] opened 2018-08-07 17:42 UTC
The Extended 80 Column / AppleColor RGB card as well as Video 7 and Le Chat Mauve support a handful of additional graphics modes. The AppleColor RGB ones are the common subset of most interest:

Mode 1: Mono 560x192 (i.e. DHR in mono mode)
Mode 2: Color 140x192 (i.e. normal DHR)
Mode 3: Mixed (high bit forces mono on a byte by byte basis)

These are accessed by hitting AN3 in the right sequence with 80COL, per the manual ftp://ftp.apple.asimov.net/pub/apple_II/documentation/hardware/video/Ext80ColumnAppleColorCard.pdf

Mode 3 is technically interesting but poorly documented - we lack good reference images to know exactly how things should appear on the boundary.

Mode 1 is useful for apps that use DHR in monochrome, like Apple II DeskTop / MouseDesk, which initializes the mode, freeing the user from hitting that pesky mono/color toggle. This is the one I'm most interested in emulators supporting. 

Given the number of video add-ons that support this capability, and that it was implemented by a specific handshake unlikely to be triggered by existing code, it seems like it would be reasonable to add to AppleWin in isolation w/o claiming full support for emulation of any particular card. I'd be satisfied by Mode 1/2 only.

**Comment by tomcw** [comment] 2018-08-08 21:01
I'm going to move these comments to #523, and close this issue as a duplicate of the other.

**Comment by tomcw** [comment] 2018-08-08 21:04
Closed as duplicate of #523.

**Closed by tomcw** 2018-08-08 21:04 UTC
Labels: duplicate
