### ISSUE TITLE
-d1 command line argument causes app to quickly exit

### ISSUE THREAD

**Issue by bsturk** [AppleWin/AppleWin#276] opened 2015-04-14 21:51 UTC
Doing some testing and specifying a disk image on the command line w/ -d1 on Windows 8.1 causes the app to launch quickly and exit.  -d2 works fine and -d1 works enough to store the specified disk image as a setting (in the registry??).  Other arguments seem to be working fine (-f -no-printscreen-dialog, etc).

**Comment by tomcw** [comment] 2015-04-15 21:12
Thanks for the bug report.

I reproduced with v1.25.0.3, with this command line:
`>applewin -d1 "C:\Work\Images\archon_i.dsk"`

And I can reproduce with a release build from the HEAD of master.

But trying with a release build from `savestate` branch works OK.

The crash occurs in `FrameDrawDiskStatus( HDC passdc )`, on this line:
````
int  isProDOS = mem[ 0xBF00 ] == 0x4C;
````
This is because `WinMain()` calls `FrameRefreshStatus()`, (but is only called when inserting a disk into drive 1).

NB. `savestate` branch does a nullptr check against `mem` to avoid this crash.

**Comment by OlivierGuinart** [comment] 2015-04-20 23:00
bsturk beat me to it; I had noticed this about a week ago, could confirm only today that it was still working up to 1.24.0, and now I see it's always been reported. The only thing I can "add" (no surprise though) is that it repros with Windows 10 :)

**Comment by tomcw** [comment] 2015-04-22 15:15
Since 2 users have reported this issue, then I think it's worth creating a patch with just a fix for this issue.

I propose creating a branch from d1dddbe813826c894be36a3091561290cc08d3d4 (ie AppleWin v1.25.0.3), applying the fix (nullptr check) + bumping the version; then releasing a patch build.

**Comment by sicklittlemonkey** [comment] 2015-04-23 00:47
Fair enough.

(That's the extent of my input, sorry. But at least I'm tuning in
occasionally. ; - )

Cheers,
Nick.

**Comment by Michaelangel007** [comment] 2015-04-23 02:19
That's my code :-(

Agreed about patching + bumping the version number.

**Comment by tomcw** [comment] 2015-04-24 17:55
New release 1.24.0.5 (built with VS2005- Express):
https://github.com/AppleWin/AppleWin/releases/tag/v1.25.0.4

**Closed by tomcw** 2015-04-24 17:55 UTC
Labels: 1.25.0.3, bug

**Comment by OlivierGuinart** [comment] 2015-04-24 18:56
Checked fixed on Windows 10 Preview Build 10106. Back on track with my makefile without hacks, thank you!

**Comment by tomcw** [comment] 2015-04-25 07:54
Thanks for verifying this.
