### ISSUE TITLE
Support for Apple Sauce .  .WOZ file support

### ISSUE THREAD

**Issue by H82lose** [AppleWin/AppleWin#550] opened 2018-03-25 01:35 UTC
Hello ,

   Just curious if there have been any progress with AppleWin in regards to reading .WOZ files for the Apple Sauce Project?  I know alot of time has been invested in this awesome hardware project.

   Thank you and I look forward to any and all replys.

   Patrick.

**Comment by sicklittlemonkey** [comment] 2018-03-25 02:01
Well, I asked John for sample WOZ files, and he said to wait a few days...
Nothing came off it. I guess I need to chase him up, but life has been busy.

He's published the spec, but he needs to upload a WOZ image of any public
domain disk just so we have a sample to work with. Not much to ask I would
have thought. It's a shame, as it seems he's worked closely with the author
of Virtual II for the Mac.

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment] 2018-03-25 02:38
OK, so John sent some WOZ images. I'll share these with Michael and Tom,
and we'll see what happens.

Cheers,
Nick.

**Comment by H82lose** [comment] 2018-03-25 02:40
Thanks Nick I'm sure something will transpire 😃

Sent from the Yahoo Mail app. Get yours! 
 
  On Sat, Mar 24, 2018 at 7:38 PM, Nick Westgate<notifications@github.com> wrote:   OK, so John sent some WOZ images. I'll share these with Michael and Tom,
and we'll see what happens.

Cheers,
Nick.

**Comment by tomcw** [comment] 2018-04-01 15:34
Closing, as duplicate of #544.

**Closed by tomcw** 2018-04-01 15:34 UTC
Labels: duplicate

**Comment by H82lose** [comment] 2018-04-02 17:56
Hi guys. I believe John sent so.E sample .WOZ file formats to you ? For Apple Win. This will be for the project Apple Sauce.  Just curious if the new file format has been implemented into Apple Win. 

Tha k you and I look forward to your Reply. 

Patrick

**Comment by tomcw** [comment] 2018-04-02 19:28
Hi Patrick,
There's been no work on supporting .WOZ so far.
I closed this issue purely because it's a duplicate of a prior one (#544) that I'd opened.

**Comment by H82lose** [comment] 2018-04-08 21:46
Hi guys. Just checking how things are going in regards to .WOZ disk image support in applewin. 

Thanks
Patrick

**Comment by tomcw** [comment] 2018-04-09 20:14
Patrick - no further progress. But you seem pretty keen for this!
I've got a backlog of work that didn't include this. Can you convince me why I should switch to looking at this? (NB. Usual real-world work/life caveats apply - so no promises)
