### ISSUE TITLE
RTS freezing

### ISSUE THREAD

**Issue by Xfactor96** [AppleWin/AppleWin#607] opened 2019-01-05 20:19 UTC
i don't know why, but in AppleWin's latest release, using the RTS command in the monitor freezes the emulator. I've used different settings different versions of the apple II and it's the same issue each time.

can someone please help as i'm new to github

**Comment by tomcw** [comment] 2019-01-05 21:42
Can say which specific version of AppleWin you are using?
And you can give precise reproducible steps? (eg. you can create a save-state using F11 from within the debugger at the point where you are doing the RTS)

AFAIK, the debugger's RTS command will just set a breakpoint at the last 16-bit word on the stack. If the code does things like PLA before the next RTS, then the breakpoint will be set at the wrong address, and so will fail to trigger.

**Comment by Xfactor96** [comment] 2019-01-05 23:19
1.27.10.0 and the code is as from assembly lines page 15
Assembly Lines: The Complete Book : Roger Wagner : Free Download, Borrow, and Streaming : Internet Archive


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Assembly Lines: The Complete Book : Roger Wagner : Free Download, Borrow...

Roger Wagner’s Assembly Lines articles originally appeared in Softalk magazine from October 1980 to June 1983. T...
 |

 |

 |





    On ‎Saturday‎, ‎January‎ ‎5‎, ‎2019‎ ‎01‎:‎42‎:‎39‎ ‎PM‎ ‎PST, TomCh <notifications@github.com> wrote:  
 
 
Can say which specific version of AppleWin you are using?
And you can give precise reproducible steps? (eg. you can create a save-state using F11 from within the debugger at the point where you are doing the RTS)

AFAIK, the debugger's RTS command will just set a breakpoint at the last 16-bit word on the stack. If the code does things like PLA before the next RTS, then the breakpoint will be set at the wrong address, and so will fail to trigger.

**Comment by tomcw** [comment] 2019-01-06 09:55
OK, I found that page here:
https://books.google.co.uk/books?id=ELshrgEACAAJ&pg=PA23&source=gbs_selected_pages&cad=2#v=onepage&q&f=false

And the code is just:
```
300: JSR BELL ; $FBDD
     RTS
```

300: 20 DD FB 60

**Comment by tomcw** [comment] 2019-01-06 10:12
I tested this, and it's working for me:

1. Enter monitor (CALL-151) and paste in the above code (300: 20 DD FB 60)
2. Set a breakpoint at 300 (F7, then "bp 300", F7)
3. Run to start of code: 300G (enters debugger and stops at 300)
4. Single step the `JSR $FBDD` by pressing SPACE. You can now see the return address on the stack:
![stack](https://user-images.githubusercontent.com/6696896/50734704-e3714d80-119a-11e9-86a4-bdb7888480e7.PNG)
5. Use the "rts" command, and the 6502 will run until address $303.

NB. If you try to use "rts" before stepping the `JSR $FBDD`, then the return address will be in the ROM. For me (using Model="Enhanced Apple //e") it stops at $FF85.

**Comment by Xfactor96** [comment] 2019-01-06 22:54
maybe it's me, but I've run the test thrice and it still hangs. can you post a video?

**Comment by tomcw** [comment] 2019-01-07 12:09
OK, here's a quick video: [AW-video.zip](https://github.com/AppleWin/AppleWin/files/2732660/AW-video.zip)
NB. at 50s, I press space to single-step.

**Comment by tomcw** [comment] 2019-04-06 08:15
@Xfactor96 - did the video help?

**Comment by tomcw** [comment] 2019-04-14 14:24
Classifying as a Question (but equally could have been Invalid).
Closing due to lack of response.

**Closed by tomcw** 2019-04-14 14:24 UTC
Labels: question
