### ISSUE TITLE
RGB Double-Hires looks strange?

### ISSUE THREAD

**Issue by bbbradsmith** [AppleWin/AppleWin#1008] opened 2021-12-10 22:49 UTC
Looking at Prince of Persia's title screen in "Color (RGB Card/Monitor)" it looks very different than in past versions of the emulatorm where it was called "Color (RGB Monitor)".

New: 1ab0d56
![Prince of Persia (rebuilt from source code) side B_000000000](https://user-images.githubusercontent.com/13027631/145649000-aeb06e75-7dd6-48bc-9294-0cb5af7adce8.png)

Old: d9f3d1e
![Prince of Persia (rebuilt from source code) side B_000000001](https://user-images.githubusercontent.com/13027631/145649667-ea57aaf1-7727-4032-b6a4-c70972bd88eb.png)

So the new version seems to fill every 4 dots with a single colour in double-hires. Is that how the RGB card hardware worked with double-hires, and the emulation just wasn't accurate before, or is the illegible copyright line indicating a problem? (Apologies for submitting an issue like this without knowing what the hardware _should_ be doing. I do not own an Apple II RGB card or monitor.)

I also notice during the introduction sequence of Prince of Persia it occasionally displays a full screen page of random blocks, presumable in lores video mode, that I believe appeared as just a solid black screen previously. I assume this is a related problem.

As a side note: I can't figure out why, but screenshot filenames often seem to be taken from disk 2? Often with single disk programs I have something else unrelated left in that slot, and it's confusing to figure out where the screenshot went.

**Comment by bbbradsmith** [comment] 2021-12-10 23:26
I found this video of a monitor used with a Digicard RGB card, which does seem to duplicate the "new" behaviour. (Photos of this Prince of Persia screen, and others like Maniac Mansion show resulting illegible text in Double-Hires.)

https://www.youtube.com/watch?v=X8HMnRuc_t8

So, I guess that indicates that it's accurate, at least for that RGB card.

If this is just normal RGB card behaviour for double-hires feel free to close the issue. The difference was startling to me when I saw it.

(The transition screen of random colours in lores might still indicate an issue, though? It occurs after the introduction text, before the switch to a hires animated screen with the princess.)

**Comment by tomcw** [comment] 2021-12-11 14:08
>So, I guess that indicates that it's accurate, at least for that RGB card.

Yes, that's right - it's accurate for the RGB card, and you get these chunky 4-wide pixels in DHGR. The mode is called 140-color pixel mode.

btw, For RGB cards, 3 other modes exist for displaying DHGR: B&W, MIXED and 160-color pixel modes.
There's also support for foreground & background TEXT colours.
See the AppleWin.chm help doc.

If you want non-chunky (colour) DHGR, then select: "Color (Composite Idealized)", "Color (Composite Monitor)" or "Color TV" display modes.

>The transition screen of random colours in lores might still indicate an issue, though? It occurs after the introduction text, before the switch to a hires animated screen with the princess.

This is due to the extended support for foreground & background TEXT colours. You'd get the same behaviour on a real RGB card.

Anyway, this is all expected behaviour, so I'm closing this.
(I spun off a new bug for the screenshots issue though)

**Closed by tomcw** 2021-12-11 14:08 UTC
