### ISSUE TITLE
How to I turn the green numbers off?

### ISSUE THREAD

**Issue by Cibomatto2002** [AppleWin/AppleWin#489] opened 2017-10-01 16:14 UTC
There are green numbers on the right side of the screen can I turn them off? If so how.

![image](https://user-images.githubusercontent.com/21169038/31056583-8da3729c-a699-11e7-87d3-ba8c096443c2.png)

**Comment by tomcw** [comment] 2017-10-01 16:36
You can't at the moment, but #224 is tracking this.
I'll close this since it's a duplicate of that one.

**Closed by tomcw** 2017-10-01 16:36 UTC
