### ISSUE TITLE
High graphics color not accurate and not solid

### ISSUE THREAD

**Issue by phed001** [AppleWin/AppleWin#566] opened 2018-06-11 20:22 UTC
Tried a programming language called APEX, the color on the graphics screen is not accurate and not solid.
Tried this on Apple Oasis http://apple2.emuunlim.com/DOWNLOAD.HTM
Also tried on the on line emulator https://www.scullinsteel.com/apple//e
Can use the attached disk on issue #565 . On the Prosel screen, press return to run the Apex demo. (Press ESC first if mouse is active)

**Comment by tomcw** [comment] 2018-06-11 21:14
I'm not really sure what you mean, but perhaps disable the 50% scanline video mode?
CTRL+SHIFT+F9 (or use the Configurion dialog)

**Comment by Keatah** [comment] 2018-06-11 22:36
Might mean the old graphics style with no forced artifacting..

**Comment by phed001** [comment] 2018-06-11 22:45
I already disabled the 50% scanline, and I am using color monitor mode for the video.
Test with the attached image in issue #565 with AppleWin and the online emulator [https://www.scullinsteel.com/apple//e](url) and you will notice the different.
Quick guide for the online emulator: Under the monitor, there is an open-folder icon for disk 1, hit the open-folder icon, then hit the browse button, select the TEST.DSK you downloaded and unzipped, then hit Load button. After loaded, you will notice the flashing apple at the bottom (issue #565), then press to run Apex demo, and you will notice the color which is different than AppleWin.

**Comment by sicklittlemonkey** [comment] 2018-06-12 01:48
It's interesting that you judge AppleWin's colours to be inaccurate by
comparing it to other emulators.

Those emulators do not emulate NTSC. Here's the colour table from Scullin's
emulator:
        [0x00,0x00,0x00],  // black
        [0xdd,0x00,0x33],  // 0x1 deep red
        [0x00,0x00,0x99],  // 0x2 dark blue
        [0xdd,0x00,0xdd],  // 0x3 purple
        [0x00,0x77,0x00],  // 0x4 dark green
        [0x55,0x55,0x55],  // 0x5 dark gray
        [0x23,0x22,0xff],  // 0x6 medium blue
        [0x66,0xaa,0xff],  // 0x7 light blue
        [0x88,0x55,0x22],  // 0x8 brown
        [0xff,0x66,0x00],  // 0x9 orange
        [0xaa,0xaa,0xaa],  // 0xa light gray
        [0xff,0x99,0x88],  // 0xb pink
        [0x00,0xdd,0x00],  // 0xc green
        [0xff,0xff,0x00],  // 0xd yellow
        [0x00,0xff,0x99],  // 0xe aquamarine
        [0xff,0xff,0xff]   // 0xf white

That's a classic set of values that KEGS used to use (and probably other
emulators too).
It was a popular emulation topic, but I don't think anyone had calculated
the colours.
The greys should be the same on a II or //e - only different on a IIgs or
RGB card.

NTSC emulation changes all that. Go here and play with the controls:
https://zellyn.github.io/apple2shader/

For your "not solid" issue, play with the "Luma Bandwidth" control.
AppleWin's NTSC emulation has a bunch of fixed parameters.
Hopefully one day we can adopt this kind of GPU-based emulation.

Cheers,
Nick.

**Comment by tomcw** [comment] 2018-06-12 17:30
Sounds like a duplicate of #357?

**Comment by tomcw** [comment] 2018-06-19 20:35
Closing as duplicate of #357.

**Closed by tomcw** 2018-06-19 20:35 UTC
Labels: duplicate
